<?php
declare(strict_types=1);
namespace App\Modules\Tourism\Controllers;
use App\Core\Auth;use App\Core\Authorization;use App\Core\Controller;use App\Modules\Tourism\Services\TourismGuideService;use RuntimeException;use Throwable;
final class TourismGuideController extends Controller{private TourismGuideService $s;private Authorization $a;public function __construct(){$this->s=new TourismGuideService();$this->a=new Authorization();}private function allow(string $p,string $r='/tourism'):bool{try{$this->a->authorize($p);return true;}catch(RuntimeException $e){flash('error',$e->getMessage());redirect($r);return false;}}
 public function index():void{if(!$this->allow('tourism.guides.view'))return;$t=(int)Auth::tenantId();$trash=($_GET['view']??'')==='trash';$this->view('Tourism::Guides.index',['title'=>$trash?'Deleted Guides':'Local Guides','guides'=>$this->s->all($t,$trash),'trash'=>$trash]);}
 public function create():void{if(!$this->allow('tourism.guides.create','/tourism/guides'))return;$this->view('Tourism::Guides.create',['title'=>'Add Local Guide']);}
 public function store():void{if(!$this->allow('tourism.guides.create','/tourism/guides'))return;$t=(int)Auth::tenantId();try{$id=$this->s->create($t,$_POST,(int)Auth::id(),$_FILES['profile_image']??null);flash('success','Guide created successfully.');redirect('/tourism/guides/'.$id);}catch(Throwable $e){$this->view('Tourism::Guides.create',['title'=>'Add Local Guide','error'=>$e->getMessage(),'old'=>$_POST]);}}
 public function show(int $id):void{if(!$this->allow('tourism.guides.view','/tourism/guides'))return;$r=$this->s->find((int)Auth::tenantId(),$id);if(!$r)abort(404);$this->view('Tourism::Guides.show',['title'=>$r['name'],'record'=>$r]);}
 public function edit(int $id):void{if(!$this->allow('tourism.guides.edit','/tourism/guides'))return;$r=$this->s->find((int)Auth::tenantId(),$id);if(!$r)abort(404);$this->view('Tourism::Guides.edit',['title'=>'Edit Guide','record'=>$r]);}
 public function update(int $id):void{if(!$this->allow('tourism.guides.edit','/tourism/guides'))return;$t=(int)Auth::tenantId();try{$this->s->update($t,$id,$_POST,(int)Auth::id(),$_FILES['profile_image']??null);flash('success','Guide updated successfully.');redirect('/tourism/guides/'.$id);}catch(Throwable $e){$r=$this->s->find($t,$id)??$_POST;$this->view('Tourism::Guides.edit',['title'=>'Edit Guide','record'=>$r,'error'=>$e->getMessage()]);}}
 public function destroy(int $id):void{if(!$this->allow('tourism.guides.delete','/tourism/guides'))return;try{$this->s->delete((int)Auth::tenantId(),$id,(int)Auth::id());flash('success','Guide moved to Trash.');}catch(Throwable $e){flash('error',$e->getMessage());}redirect('/tourism/guides');}
 public function restore(int $id):void{if(!$this->allow('tourism.guides.delete','/tourism/guides?view=trash'))return;try{$this->s->restore((int)Auth::tenantId(),$id,(int)Auth::id());flash('success','Guide restored.');}catch(Throwable $e){flash('error',$e->getMessage());}redirect('/tourism/guides?view=trash');}
}
