<?php
declare(strict_types=1);
namespace App\Modules\Tourism\Controllers;
use App\Core\Auth;use App\Core\Authorization;use App\Core\Controller;use App\Modules\Tourism\Services\TourismPackageService;use RuntimeException;use Throwable;
final class TourismPackageController extends Controller{private TourismPackageService $s;private Authorization $a;public function __construct(){$this->s=new TourismPackageService();$this->a=new Authorization();}private function allow(string $p,string $r='/tourism'):bool{try{$this->a->authorize($p);return true;}catch(RuntimeException $e){flash('error',$e->getMessage());redirect($r);return false;}}
 public function index():void{if(!$this->allow('tourism.packages.view'))return;$t=(int)Auth::tenantId();$trash=($_GET['view']??'')==='trash';$this->view('Tourism::Packages.index',['title'=>$trash?'Deleted Tour Packages':'Tour Packages','packages'=>$this->s->all($t,$trash),'trash'=>$trash]);}
 public function create():void{if(!$this->allow('tourism.packages.create','/tourism/packages'))return;$t=(int)Auth::tenantId();$this->view('Tourism::Packages.create',['title'=>'Add Tour Package','providers'=>$this->s->providers($t),'destinations'=>$this->s->destinationsForSelect($t)]);}
 public function store():void{if(!$this->allow('tourism.packages.create','/tourism/packages'))return;$t=(int)Auth::tenantId();try{$id=$this->s->create($t,$_POST,(int)Auth::id(),$_FILES['cover_image']??null);flash('success','Tour package created successfully.');redirect('/tourism/packages/'.$id);}catch(Throwable $e){$this->view('Tourism::Packages.create',['title'=>'Add Tour Package','providers'=>$this->s->providers($t),'destinations'=>$this->s->destinationsForSelect($t),'error'=>$e->getMessage(),'old'=>$_POST]);}}
 public function show(int $id):void{if(!$this->allow('tourism.packages.view','/tourism/packages'))return;$t=(int)Auth::tenantId();$r=$this->s->find($t,$id);if(!$r)abort(404);$this->view('Tourism::Packages.show',['title'=>$r['title'],'record'=>$r,'destinations'=>$this->s->destinations($t,$id),'all_destinations'=>$this->s->destinationsForSelect($t)]);}
 public function edit(int $id):void{if(!$this->allow('tourism.packages.edit','/tourism/packages'))return;$t=(int)Auth::tenantId();$r=$this->s->find($t,$id);if(!$r)abort(404);$this->view('Tourism::Packages.edit',['title'=>'Edit Tour Package','record'=>$r,'providers'=>$this->s->providers($t),'destinations'=>$this->s->destinationsForSelect($t)]);}
 public function update(int $id):void{if(!$this->allow('tourism.packages.edit','/tourism/packages'))return;$t=(int)Auth::tenantId();try{$this->s->update($t,$id,$_POST,(int)Auth::id(),$_FILES['cover_image']??null);flash('success','Tour package updated successfully.');redirect('/tourism/packages/'.$id);}catch(Throwable $e){$r=$this->s->find($t,$id)??$_POST;$this->view('Tourism::Packages.edit',['title'=>'Edit Tour Package','record'=>$r,'providers'=>$this->s->providers($t),'destinations'=>$this->s->destinationsForSelect($t),'error'=>$e->getMessage()]);}}
 public function addDestination(int $id):void{if(!$this->allow('tourism.packages.edit','/tourism/packages/'.$id))return;try{$this->s->addDestination((int)Auth::tenantId(),$id,$_POST);flash('success','Destination added to itinerary.');}catch(Throwable $e){flash('error',$e->getMessage());}redirect('/tourism/packages/'.$id);}
 public function removeDestination(int $id,int $relationId):void{if(!$this->allow('tourism.packages.edit','/tourism/packages/'.$id))return;try{$this->s->removeDestination((int)Auth::tenantId(),$id,$relationId);flash('success','Destination removed from itinerary.');}catch(Throwable $e){flash('error',$e->getMessage());}redirect('/tourism/packages/'.$id);}
 public function destroy(int $id):void{if(!$this->allow('tourism.packages.delete','/tourism/packages'))return;try{$this->s->delete((int)Auth::tenantId(),$id,(int)Auth::id());flash('success','Tour package moved to Trash.');}catch(Throwable $e){flash('error',$e->getMessage());}redirect('/tourism/packages');}
 public function restore(int $id):void{if(!$this->allow('tourism.packages.delete','/tourism/packages?view=trash'))return;try{$this->s->restore((int)Auth::tenantId(),$id,(int)Auth::id());flash('success','Tour package restored.');}catch(Throwable $e){flash('error',$e->getMessage());}redirect('/tourism/packages?view=trash');}
}
