<?php
declare(strict_types=1);
namespace App\Modules\FreshFood\Controllers;
use App\Core\Auth;use App\Core\Authorization;use App\Core\Controller;use App\Modules\FreshFood\Services\FreshFoodProductService;use RuntimeException;use Throwable;
final class FreshFoodProductController extends Controller {private FreshFoodProductService $s;private Authorization $a;public function __construct(){$this->s=new FreshFoodProductService();$this->a=new Authorization();}private function allow(string $p,string $r='/fresh-food/products'):bool{try{$this->a->authorize($p);return true;}catch(RuntimeException $e){flash('error',$e->getMessage());redirect($r);return false;}}private function formData(int $t,int $f=0):array{return['businesses'=>$this->s->businesses($t),'categories'=>$f>0?$this->s->categories($t,$f):[]];}public function index():void{if(!$this->allow('fresh_food.products.view'))return;$t=(int)Auth::tenantId();$trash=($_GET['view']??'')==='trash';$this->view('FreshFood::Products.index',['title'=>$trash?'Deleted Fresh Food Products':'Fresh Food Products','products'=>$this->s->all($t,$trash),'trash'=>$trash]);}public function categories(int $freshFoodId):void{
if(!$this->allow('fresh_food.products.create'))return;
$t=(int)Auth::tenantId();
header('Content-Type: application/json; charset=UTF-8');
try{echo json_encode($this->s->categories($t,$freshFoodId),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);}
catch(Throwable $e){http_response_code(500);echo json_encode(['error'=>'Unable to load categories.']);}
exit;
}
public function create():void{if(!$this->allow('fresh_food.products.create'))return;$t=(int)Auth::tenantId();$this->view('FreshFood::Products.create',['title'=>'Add Fresh Food Product',...$this->formData($t)]);}public function store():void{if(!$this->allow('fresh_food.products.create'))return;$t=(int)Auth::tenantId();try{$this->s->create($t,$_POST,(int)Auth::id());flash('success','Product created.');redirect('/fresh-food/products');}catch(Throwable $e){$f=(int)($_POST['fresh_food_id']??0);$this->view('FreshFood::Products.create',['title'=>'Add Fresh Food Product',...$this->formData($t,$f),'error'=>$e->getMessage(),'old'=>$_POST]);}}public function edit(int $id):void{if(!$this->allow('fresh_food.products.edit'))return;$t=(int)Auth::tenantId();$r=$this->s->find($t,$id);if(!$r)abort(404);$this->view('FreshFood::Products.edit',['title'=>'Edit Fresh Food Product','record'=>$r,...$this->formData($t,(int)$r['fresh_food_id'])]);}public function update(int $id):void{if(!$this->allow('fresh_food.products.edit'))return;$t=(int)Auth::tenantId();try{$this->s->update($t,$id,$_POST,(int)Auth::id());flash('success','Product updated.');redirect('/fresh-food/products');}catch(Throwable $e){$f=(int)($_POST['fresh_food_id']??0);$this->view('FreshFood::Products.edit',['title'=>'Edit Fresh Food Product','record'=>$_POST,...$this->formData($t,$f),'error'=>$e->getMessage()]);}}public function destroy(int $id):void{if(!$this->allow('fresh_food.products.delete'))return;try{$this->s->delete((int)Auth::tenantId(),$id,(int)Auth::id());flash('success','Product deleted.');}catch(Throwable $e){flash('error',$e->getMessage());}redirect('/fresh-food/products');}public function restore(int $id):void{if(!$this->allow('fresh_food.products.delete','/fresh-food/products?view=trash'))return;try{$this->s->restore((int)Auth::tenantId(),$id,(int)Auth::id());flash('success','Product restored.');}catch(Throwable $e){flash('error',$e->getMessage());}redirect('/fresh-food/products?view=trash');}}
