<?php
declare(strict_types=1);
include __DIR__ . '/../Shared/member-desktop.css.php';
include __DIR__ . '/../Shared/member-desktop-header.php';

$basePath=rtrim((string)config('app.base_path'),'/');$service=is_array($service??null)?$service:[];$vehicles=is_array($vehicles??null)?$vehicles:[];$q=is_array($query??null)?$query:[];$csrf=$csrf??null;
function maVe(mixed $v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');} function maVm(mixed $v):string{return '₹'.number_format((float)$v,2);} function maVmode(string $m):string{return match(strtoupper($m)){ 'PER_RIDE'=>'Per Ride','PER_KM'=>'Per KM','PER_DAY'=>'Per Day / Rental','PER_KM_WITH_MINIMUM'=>'Per KM with Minimum','CUSTOM_QUOTE'=>'Custom Quote',default=>$m};}
$trip=strtoupper((string)($q['trip_type']??'ROUND_TRIP'));$round=$trip==='ROUND_TRIP';
$pickupDate=(string)($q['pickup_date']??date('Y-m-d'));$pickupTime=(string)($q['pickup_time']??date('H:i'));$returnDate=(string)($q['return_date']??'');$returnTime=(string)($q['return_time']??'');
$scheduled=$pickupDate&&$pickupTime?$pickupDate.' '.$pickupTime.':00':null;$returnScheduled=$round&&$returnDate&&$returnTime?$returnDate.' '.$returnTime.':00':null;
?>
<style>
.ma-v{max-width:560px;margin:auto;padding:14px 14px 105px;color:#14251f}.ma-v *{box-sizing:border-box}.ma-vhead{display:flex;gap:12px;align-items:center;padding:6px 2px 14px}.ma-vback{font-size:28px;text-decoration:none;color:#183b33}.ma-vhead h1{margin:0;font-size:24px}.ma-vhead p{margin:3px 0;color:#718078;font-size:12px}.ma-summary{background:#f1f8f5;border:1px solid #dbece5;border-radius:20px;padding:15px;margin-bottom:14px}.ma-summary h2{margin:0;font-size:17px}.ma-summary small{color:#667a72}.ma-summary-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}.ma-sbox{background:#fff;border-radius:13px;padding:10px;font-size:12px}.ma-sbox b{display:block;margin-top:3px}.ma-filters{display:flex;gap:8px;overflow:auto;margin:12px 0}.ma-filters button{border:1px solid #dce7e2;background:#fff;border-radius:20px;padding:9px 13px;white-space:nowrap}.ma-filters button.active{background:#087d64;color:#fff}.ma-vehicle{background:#fff;border:1px solid #e1ebe6;border-radius:20px;padding:10px;margin:11px 0;box-shadow:0 7px 22px rgba(20,57,47,.06)}.ma-vrow{display:grid;grid-template-columns:125px 1fr;gap:12px}.ma-photo{height:105px;border-radius:14px;background:linear-gradient(145deg,#dcebe6,#edf4f2);display:flex;align-items:center;justify-content:center;font-size:42px;overflow:hidden}.ma-photo img{width:100%;height:100%;object-fit:cover}.ma-vehicle h3{margin:2px 0 4px;font-size:16px}.ma-meta{color:#6d7d77;font-size:12px;line-height:1.7}.ma-price{font-weight:900;font-size:17px;margin-top:5px}.ma-rule{font-size:11px;color:#587068;margin-top:4px}.ma-select{width:100%;border:0;border-radius:12px;background:#087d64;color:#fff;padding:11px;margin-top:9px;font-weight:800}.ma-alert{background:#fff5df;border:1px solid #f0dfb7;padding:12px;border-radius:14px;font-size:12px;color:#765d22;margin-bottom:12px}.ma-nav{position:fixed;left:50%;bottom:10px;transform:translateX(-50%);width:min(540px,calc(100% - 20px));background:rgba(255,255,255,.96);border:1px solid #e1ebe7;box-shadow:0 10px 30px rgba(0,0,0,.12);border-radius:22px;display:grid;grid-template-columns:repeat(4,1fr);padding:7px;z-index:30}.ma-nav a{text-decoration:none;color:#73827c;text-align:center;padding:8px 3px;font-size:11px;font-weight:700}.ma-nav a.active{color:#087d64}.ma-nav i{display:block;font-style:normal;font-size:20px;margin-bottom:2px}
</style>
<div class="ma-v"><header class="ma-vhead"><a class="ma-vback" href="<?=maVe($basePath)?>/member/taxi">‹</a><div><h1>Select a Taxi</h1><p>Available vehicles for your trip</p></div></header>
<section class="ma-summary"><h2><?=maVe($q['pickup_address']??'Pickup')?> → <?=maVe($q['destination_address']??'Destination')?></h2><small><?=maVe($pickupDate)?> · <?=maVe($pickupTime)?> <?= $round?'→ '.maVe($returnDate).' · '.maVe($returnTime):'· One Way' ?></small><div class="ma-summary-grid"><div class="ma-sbox">Service<b><?=maVe($service['name']??'Taxi')?></b></div><div class="ma-sbox">Pricing<b><?=maVmode((string)($service['pricing_mode']??''))?></b></div></div></section>
<?php if(!empty($error)):?><div class="ma-alert"><?=maVe($error)?></div><?php endif; ?>
<div class="ma-filters"><button class="active" type="button" data-seat="0">All</button><button type="button" data-seat="4">4+ Seater</button><button type="button" data-seat="7">7+ Seater</button><button type="button" data-seat="12">12+ Seater</button></div>
<?php foreach($vehicles as $v): $img=!empty($v['photo_path'])?$basePath.'/'.ltrim((string)$v['photo_path'],'/') : ''; $model=trim(($v['make']??'').' '.($v['model']??'')); ?>
<article class="ma-vehicle" data-seats="<?=maVe($v['seating_capacity']??0)?>"><div class="ma-vrow"><div class="ma-photo"><?php if($img):?><img src="<?=maVe($img)?>" alt="<?=maVe($model?:'Taxi')?>"><?php else:?>🚕<?php endif;?></div><div><h3><?=maVe($model?:($v['vehicle_type']??'Taxi'))?></h3><div class="ma-meta">👥 <?=maVe($v['seating_capacity']??'-')?> Seater · <?=maVe($v['vehicle_type']??'Vehicle')?><br>✓ Active taxi · <?=!empty($v['driver_available'])?'Driver available':'Driver assignment by operator'?></div><div class="ma-price"><?php if(($service['pricing_mode']??'')==='PER_DAY'):?><?=maVm($service['daily_rate']??0)?> / day<?php elseif(($service['pricing_mode']??'')==='CUSTOM_QUOTE'):?>Quote required<?php else:?>From <?=maVm($service['base_fare']??0)?><?php endif;?></div><div class="ma-rule"><?php if(($service['pricing_mode']??'')==='PER_RIDE'):?><?=number_format((float)($service['included_km']??0),2)?> km included<?php elseif(in_array(($service['pricing_mode']??''),['PER_KM','PER_KM_WITH_MINIMUM'],true)):?><?=maVm($service['per_km']??0)?>/km<?php endif;?><?php if((float)($service['extra_km_rate']??0)>0):?> · <?=maVm($service['extra_km_rate'])?>/km extra<?php endif;?></div></div></div>
<form method="post" action="<?=maVe($basePath)?>/member/taxi/book"><input type="hidden" name="_token" value="<?=maVe($csrf ?: '')?>"><input type="hidden" name="service_id" value="<?=maVe($service['id'])?>"><input type="hidden" name="vehicle_id" value="<?=maVe($v['id'])?>"><input type="hidden" name="trip_type" value="<?=maVe($trip)?>"><input type="hidden" name="pickup_address" value="<?=maVe($q['pickup_address']??'')?>"><input type="hidden" name="pickup_lat" value="<?=maVe($q['pickup_lat']??'')?>"><input type="hidden" name="pickup_lng" value="<?=maVe($q['pickup_lng']??'')?>"><input type="hidden" name="destination_address" value="<?=maVe($q['destination_address']??'')?>"><input type="hidden" name="destination_lat" value="<?=maVe($q['destination_lat']??'')?>"><input type="hidden" name="destination_lng" value="<?=maVe($q['destination_lng']??'')?>"><input type="hidden" name="scheduled_at" value="<?=maVe($scheduled)?>"><input type="hidden" name="return_scheduled_at" value="<?=maVe($returnScheduled)?>"><input type="hidden" name="notes" value="<?=maVe($q['notes']??'')?>"><button class="ma-select" type="submit">Select &amp; Book This Taxi →</button></form></article>
<?php endforeach; if(!$vehicles):?><div class="ma-alert">No active taxis are available for this service right now. Please try another service or seating option.</div><?php endif;?><?php include __DIR__ . '/../Shared/restaurant-cart-widget.php'; ?>
<?php include __DIR__ . '/../Shared/member-notification-widget.php'; ?>
</div>
<nav class="ma-nav"><a href="<?=maVe($basePath)?>/member"><i>⌂</i>Home</a><a class="active" href="<?=maVe($basePath)?>/member/taxi"><i>🚕</i>Services</a><a href="<?=maVe($basePath)?>/member/bookings"><i>▣</i>Bookings</a><a href="<?=maVe($basePath)?>/member/profile"><i>♙</i>Profile</a></nav>
<script>document.querySelectorAll('[data-seat]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-seat]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const n=+b.dataset.seat;document.querySelectorAll('.ma-vehicle').forEach(v=>v.style.display=!n||+v.dataset.seats>=n?'block':'none')}));</script>
