<?php
declare(strict_types=1);
namespace App\Modules\CommercialRental\Models;
use App\Core\Database;
final class CommercialRentalProvider {
 private Database $db; public function __construct(){ $this->db=app()->get('db'); }
 public function all(int $tenantId):array{return $this->db->fetchAll("SELECT p.*,b.name AS business_name,b.slug AS business_slug FROM commercial_rental_providers p INNER JOIN businesses b ON b.id=p.business_id AND b.tenant_id=p.tenant_id WHERE p.tenant_id=? AND p.deleted_at IS NULL AND b.deleted_at IS NULL ORDER BY p.id DESC",[$tenantId]);}
 public function find(int $tenantId,int $id):?array{return $this->db->fetch("SELECT p.*,b.name AS business_name,b.slug AS business_slug,b.phone AS business_phone,b.email AS business_email FROM commercial_rental_providers p INNER JOIN businesses b ON b.id=p.business_id AND b.tenant_id=p.tenant_id WHERE p.tenant_id=? AND p.id=? AND p.deleted_at IS NULL AND b.deleted_at IS NULL LIMIT 1",[$tenantId,$id]);}
 public function create(int $tenantId,array $d,int $uid):int{$this->db->execute("INSERT INTO businesses(uuid,tenant_id,name,slug,business_type,phone,email,address,city,district,state,postal_code,status,created_by,updated_by) VALUES(UUID(),?,?,?,?,?,?,?,?,?,?,?,?,?,?)",[$tenantId,$d['business_name'],$d['business_slug'],'commercial_rental',$d['phone'],$d['email'],$d['address'],$d['city'],$d['district'],$d['state'],$d['postal_code'],$d['status'],$uid,$uid]);$bid=(int)$this->db->lastInsertId();$this->db->execute("INSERT INTO commercial_rental_providers(uuid,tenant_id,business_id,legal_name,description,phone,email,address,city,district,state,postal_code,latitude,longitude,service_areas,status,created_by,updated_by) VALUES(UUID(),?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",[$tenantId,$bid,$d['legal_name'],$d['description'],$d['phone'],$d['email'],$d['address'],$d['city'],$d['district'],$d['state'],$d['postal_code'],$d['latitude'],$d['longitude'],$d['service_areas'],$d['status'],$uid,$uid]);return (int)$this->db->lastInsertId();}
 public function update(int $tenantId,int $id,array $d,int $uid):void{$r=$this->find($tenantId,$id);if(!$r)return;$this->db->execute("UPDATE businesses SET name=?,slug=?,phone=?,email=?,address=?,city=?,district=?,state=?,postal_code=?,status=?,updated_by=? WHERE tenant_id=? AND id=? AND deleted_at IS NULL",[$d['business_name'],$d['business_slug'],$d['phone'],$d['email'],$d['address'],$d['city'],$d['district'],$d['state'],$d['postal_code'],$d['status'],$uid,$tenantId,(int)$r['business_id']]);$this->db->execute("UPDATE commercial_rental_providers SET legal_name=?,description=?,phone=?,email=?,address=?,city=?,district=?,state=?,postal_code=?,latitude=?,longitude=?,service_areas=?,status=?,updated_by=? WHERE tenant_id=? AND id=? AND deleted_at IS NULL",[$d['legal_name'],$d['description'],$d['phone'],$d['email'],$d['address'],$d['city'],$d['district'],$d['state'],$d['postal_code'],$d['latitude'],$d['longitude'],$d['service_areas'],$d['status'],$uid,$tenantId,$id]);}
 public function softDelete(int $tenantId,int $id,int $uid):void{$r=$this->find($tenantId,$id);if(!$r)return;$this->db->execute("UPDATE commercial_rental_providers SET deleted_at=NOW(),updated_by=? WHERE tenant_id=? AND id=? AND deleted_at IS NULL",[$uid,$tenantId,$id]);$this->db->execute("UPDATE businesses SET deleted_at=NOW(),updated_by=? WHERE tenant_id=? AND id=? AND deleted_at IS NULL",[$uid,$tenantId,(int)$r['business_id']]);}
 public function businessNameExists(int $tenantId,string $name,?int $ignore=null):bool{$sql="SELECT p.id FROM commercial_rental_providers p INNER JOIN businesses b ON b.id=p.business_id AND b.tenant_id=p.tenant_id WHERE p.tenant_id=? AND b.name=? AND p.deleted_at IS NULL AND b.deleted_at IS NULL";$params=[$tenantId,$name];if($ignore!==null){$sql.=" AND p.id<>?";$params[]=$ignore;}return $this->db->fetch($sql.' LIMIT 1',$params)!==null;}
 public function slugExists(int $tenantId,string $slug,?int $ignore=null):bool{$sql="SELECT p.id FROM commercial_rental_providers p INNER JOIN businesses b ON b.id=p.business_id AND b.tenant_id=p.tenant_id WHERE p.tenant_id=? AND b.slug=? AND p.deleted_at IS NULL AND b.deleted_at IS NULL";$params=[$tenantId,$slug];if($ignore!==null){$sql.=" AND p.id<>?";$params[]=$ignore;}return $this->db->fetch($sql.' LIMIT 1',$params)!==null;}
 public function count(int $tenantId):int{$r=$this->db->fetch("SELECT COUNT(*) c FROM commercial_rental_providers WHERE tenant_id=? AND deleted_at IS NULL",[$tenantId]);return (int)($r['c']??0);}
}
