-- ManipurApp Tourism Module v0.1.0
-- Foundation: providers, destinations, stays and room types.

SET NAMES utf8mb4;
START TRANSACTION;

CREATE TABLE IF NOT EXISTS tourism_providers (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid CHAR(36) NOT NULL,
    tenant_id BIGINT UNSIGNED NOT NULL,
    business_id BIGINT UNSIGNED NOT NULL,
    provider_type ENUM('HOTEL','LODGE','HOMESTAY','RESORT','GUEST_HOUSE','TOUR_OPERATOR','TRAVEL_AGENCY','OTHER') NOT NULL DEFAULT 'OTHER',
    legal_name VARCHAR(255) DEFAULT NULL,
    description TEXT DEFAULT NULL,
    phone VARCHAR(30) DEFAULT NULL,
    email VARCHAR(255) DEFAULT NULL,
    address VARCHAR(500) DEFAULT NULL,
    city VARCHAR(150) DEFAULT NULL,
    district VARCHAR(150) DEFAULT NULL,
    state VARCHAR(150) DEFAULT 'Manipur',
    postal_code VARCHAR(20) DEFAULT NULL,
    latitude DECIMAL(10,7) DEFAULT NULL,
    longitude DECIMAL(10,7) DEFAULT NULL,
    status ENUM('Active','Inactive','Suspended') NOT NULL DEFAULT 'Active',
    created_by BIGINT UNSIGNED DEFAULT NULL,
    updated_by BIGINT UNSIGNED DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_tourism_provider_uuid (uuid),
    UNIQUE KEY uq_tourism_provider_business (tenant_id,business_id),
    KEY idx_tourism_provider_location (tenant_id,latitude,longitude),
    KEY idx_tourism_provider_district (tenant_id,district),
    KEY idx_tourism_provider_status (tenant_id,status),
    KEY idx_tourism_provider_deleted (tenant_id,deleted_at),
    CONSTRAINT fk_tourism_provider_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_tourism_provider_business FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE,
    CONSTRAINT fk_tourism_provider_created FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_tourism_provider_updated FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tourism_destinations (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid CHAR(36) NOT NULL,
    tenant_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(180) NOT NULL,
    slug VARCHAR(200) NOT NULL,
    description TEXT DEFAULT NULL,
    district VARCHAR(150) DEFAULT NULL,
    city VARCHAR(150) DEFAULT NULL,
    state VARCHAR(150) DEFAULT 'Manipur',
    best_time_to_visit VARCHAR(255) DEFAULT NULL,
    suggested_duration VARCHAR(100) DEFAULT NULL,
    latitude DECIMAL(10,7) DEFAULT NULL,
    longitude DECIMAL(10,7) DEFAULT NULL,
    cover_image_path VARCHAR(500) DEFAULT NULL,
    status ENUM('Active','Inactive') NOT NULL DEFAULT 'Active',
    created_by BIGINT UNSIGNED DEFAULT NULL,
    updated_by BIGINT UNSIGNED DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_tourism_destination_uuid (uuid),
    UNIQUE KEY uq_tourism_destination_slug (tenant_id,slug),
    KEY idx_tourism_destination_location (tenant_id,latitude,longitude),
    KEY idx_tourism_destination_district (tenant_id,district),
    KEY idx_tourism_destination_status (tenant_id,status),
    KEY idx_tourism_destination_deleted (tenant_id,deleted_at),
    CONSTRAINT fk_tourism_destination_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_tourism_destination_created FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_tourism_destination_updated FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tourism_stays (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid CHAR(36) NOT NULL,
    tenant_id BIGINT UNSIGNED NOT NULL,
    provider_id BIGINT UNSIGNED NOT NULL,
    destination_id BIGINT UNSIGNED DEFAULT NULL,
    name VARCHAR(180) NOT NULL,
    slug VARCHAR(200) NOT NULL,
    stay_type ENUM('HOTEL','LODGE','HOMESTAY','GUEST_HOUSE','RESORT','HOSTEL','VILLA','CAMP','OTHER') NOT NULL DEFAULT 'HOTEL',
    description TEXT DEFAULT NULL,
    phone VARCHAR(30) DEFAULT NULL,
    email VARCHAR(255) DEFAULT NULL,
    address VARCHAR(500) DEFAULT NULL,
    city VARCHAR(150) DEFAULT NULL,
    district VARCHAR(150) DEFAULT NULL,
    state VARCHAR(150) DEFAULT 'Manipur',
    postal_code VARCHAR(20) DEFAULT NULL,
    latitude DECIMAL(10,7) DEFAULT NULL,
    longitude DECIMAL(10,7) DEFAULT NULL,
    check_in_time TIME DEFAULT NULL,
    check_out_time TIME DEFAULT NULL,
    amenities TEXT DEFAULT NULL,
    starting_price_per_night DECIMAL(12,2) DEFAULT NULL,
    logo_path VARCHAR(500) DEFAULT NULL,
    cover_image_path VARCHAR(500) DEFAULT NULL,
    status ENUM('Draft','Pending','Active','Inactive','Suspended') NOT NULL DEFAULT 'Draft',
    created_by BIGINT UNSIGNED DEFAULT NULL,
    updated_by BIGINT UNSIGNED DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_tourism_stay_uuid (uuid),
    UNIQUE KEY uq_tourism_stay_slug (tenant_id,slug),
    KEY idx_tourism_stay_provider (tenant_id,provider_id),
    KEY idx_tourism_stay_destination (tenant_id,destination_id),
    KEY idx_tourism_stay_location (tenant_id,latitude,longitude),
    KEY idx_tourism_stay_status (tenant_id,status),
    KEY idx_tourism_stay_deleted (tenant_id,deleted_at),
    CONSTRAINT fk_tourism_stay_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_tourism_stay_provider FOREIGN KEY (provider_id) REFERENCES tourism_providers(id) ON DELETE CASCADE,
    CONSTRAINT fk_tourism_stay_destination FOREIGN KEY (destination_id) REFERENCES tourism_destinations(id) ON DELETE SET NULL,
    CONSTRAINT fk_tourism_stay_created FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_tourism_stay_updated FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tourism_stay_room_types (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid CHAR(36) NOT NULL,
    tenant_id BIGINT UNSIGNED NOT NULL,
    stay_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(180) NOT NULL,
    description TEXT DEFAULT NULL,
    bed_type VARCHAR(100) DEFAULT NULL,
    max_guests SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    quantity SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    price_per_night DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    status ENUM('Active','Inactive') NOT NULL DEFAULT 'Active',
    created_by BIGINT UNSIGNED DEFAULT NULL,
    updated_by BIGINT UNSIGNED DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_tourism_room_uuid (uuid),
    KEY idx_tourism_room_stay (tenant_id,stay_id),
    KEY idx_tourism_room_status (tenant_id,status),
    KEY idx_tourism_room_deleted (tenant_id,deleted_at),
    CONSTRAINT fk_tourism_room_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_tourism_room_stay FOREIGN KEY (stay_id) REFERENCES tourism_stays(id) ON DELETE CASCADE,
    CONSTRAINT fk_tourism_room_created FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_tourism_room_updated FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

COMMIT;
