SET NAMES utf8mb4;
START TRANSACTION;

CREATE TABLE IF NOT EXISTS tourism_packages (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid CHAR(36) NOT NULL,
    tenant_id BIGINT UNSIGNED NOT NULL,
    provider_id BIGINT UNSIGNED DEFAULT NULL,
    title VARCHAR(220) NOT NULL,
    slug VARCHAR(240) NOT NULL,
    description TEXT DEFAULT NULL,
    duration_days SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    duration_nights SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    pricing_type ENUM('PER_PERSON','PER_GROUP') NOT NULL DEFAULT 'PER_PERSON',
    base_price DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    discount_price DECIMAL(12,2) DEFAULT NULL,
    max_travellers SMALLINT UNSIGNED DEFAULT NULL,
    cover_image_path VARCHAR(500) DEFAULT NULL,
    status ENUM('Draft','Pending','Active','Inactive','Suspended') NOT NULL DEFAULT 'Draft',
    created_by BIGINT UNSIGNED DEFAULT NULL,
    updated_by BIGINT UNSIGNED DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_tourism_package_uuid (uuid),
    UNIQUE KEY uq_tourism_package_slug (tenant_id,slug),
    KEY idx_tourism_package_provider (tenant_id,provider_id),
    KEY idx_tourism_package_status (tenant_id,status),
    KEY idx_tourism_package_deleted (tenant_id,deleted_at),
    CONSTRAINT fk_tourism_package_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_tourism_package_provider FOREIGN KEY (provider_id) REFERENCES tourism_providers(id) ON DELETE SET NULL,
    CONSTRAINT fk_tourism_package_created FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_tourism_package_updated FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tourism_package_destinations (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid CHAR(36) NOT NULL,
    tenant_id BIGINT UNSIGNED NOT NULL,
    package_id BIGINT UNSIGNED NOT NULL,
    destination_id BIGINT UNSIGNED NOT NULL,
    day_number SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    sequence_no SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    notes VARCHAR(500) DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_tourism_package_destination (package_id,destination_id),
    UNIQUE KEY uq_tourism_package_destination_uuid (uuid),
    KEY idx_tourism_package_destination_tenant (tenant_id),
    KEY idx_tourism_package_destination_destination (tenant_id,destination_id),
    CONSTRAINT fk_tourism_package_destination_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_tourism_package_destination_package FOREIGN KEY (package_id) REFERENCES tourism_packages(id) ON DELETE CASCADE,
    CONSTRAINT fk_tourism_package_destination_destination FOREIGN KEY (destination_id) REFERENCES tourism_destinations(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tourism_guides (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid CHAR(36) NOT NULL,
    tenant_id BIGINT UNSIGNED NOT NULL,
    business_id BIGINT UNSIGNED DEFAULT NULL,
    name VARCHAR(180) NOT NULL,
    slug VARCHAR(200) NOT NULL,
    bio TEXT DEFAULT NULL,
    profile_image_path VARCHAR(500) DEFAULT NULL,
    phone VARCHAR(30) DEFAULT NULL,
    email VARCHAR(255) DEFAULT NULL,
    city VARCHAR(150) DEFAULT NULL,
    district VARCHAR(150) DEFAULT NULL,
    state VARCHAR(150) DEFAULT 'Manipur',
    latitude DECIMAL(10,7) DEFAULT NULL,
    longitude DECIMAL(10,7) DEFAULT NULL,
    languages TEXT DEFAULT NULL,
    specializations TEXT DEFAULT NULL,
    experience_years SMALLINT UNSIGNED DEFAULT NULL,
    price_per_day DECIMAL(12,2) DEFAULT NULL,
    verification_status ENUM('Pending','Verified','Rejected') NOT NULL DEFAULT 'Pending',
    status ENUM('Active','Inactive','Suspended') NOT NULL DEFAULT 'Active',
    created_by BIGINT UNSIGNED DEFAULT NULL,
    updated_by BIGINT UNSIGNED DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_tourism_guide_uuid (uuid),
    UNIQUE KEY uq_tourism_guide_slug (tenant_id,slug),
    KEY idx_tourism_guide_business (tenant_id,business_id),
    KEY idx_tourism_guide_location (tenant_id,latitude,longitude),
    KEY idx_tourism_guide_district (tenant_id,district),
    KEY idx_tourism_guide_status (tenant_id,status),
    KEY idx_tourism_guide_deleted (tenant_id,deleted_at),
    CONSTRAINT fk_tourism_guide_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_tourism_guide_business FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE SET NULL,
    CONSTRAINT fk_tourism_guide_created FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_tourism_guide_updated FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

COMMIT;
