<?php
declare(strict_types=1);
namespace App\Modules\Tourism\Models;
use App\Core\Database;
final class TourismProvider{
 private Database $db;public function __construct(){$this->db=app()->get('db');}
 public function all(int $t,bool $deleted=false):array{$where=$deleted?'p.deleted_at IS NOT NULL AND b.deleted_at IS NOT NULL':'p.deleted_at IS NULL AND b.deleted_at IS NULL';return $this->db->fetchAll("SELECT p.*,b.name business_name,b.slug business_slug,b.phone business_phone,b.email business_email,b.address business_address,b.city business_city,b.district business_district,b.state business_state,b.postal_code business_postal,(SELECT COUNT(*) FROM tourism_stays s WHERE s.provider_id=p.id AND s.tenant_id=p.tenant_id AND s.deleted_at IS NULL) stay_count FROM tourism_providers p INNER JOIN businesses b ON b.id=p.business_id AND b.tenant_id=p.tenant_id WHERE p.tenant_id=? AND {$where} ORDER BY p.id DESC",[$t]);}
 public function find(int $t,int $id):?array{return $this->one($t,$id,false);}public function findDeleted(int $t,int $id):?array{return $this->one($t,$id,true);}
 private function one(int $t,int $id,bool $deleted):?array{$w=$deleted?'p.deleted_at IS NOT NULL AND b.deleted_at IS NOT NULL':'p.deleted_at IS NULL AND b.deleted_at IS NULL';return $this->db->fetch("SELECT p.*,b.name business_name,b.slug business_slug,b.phone business_phone,b.email business_email,b.address business_address,b.city business_city,b.district business_district,b.state business_state,b.postal_code business_postal FROM tourism_providers p INNER JOIN businesses b ON b.id=p.business_id AND b.tenant_id=p.tenant_id WHERE p.tenant_id=? AND p.id=? AND {$w} LIMIT 1",[$t,$id]);}
 public function create(int $t,array $d,int $u):int{$this->db->execute("INSERT INTO businesses(uuid,tenant_id,name,slug,business_type,phone,email,address,city,district,state,postal_code,status,created_by,updated_by) VALUES(UUID(),?,?,?,?,?,?,?,?,?,?,?,?,?,?)",[$t,$d['business_name'],$d['business_slug'],'tourism',$d['phone'],$d['email'],$d['address'],$d['city'],$d['district'],$d['state'],$d['postal_code'],$d['status'],$u,$u]);$bid=(int)$this->db->lastInsertId();$this->db->execute("INSERT INTO tourism_providers(uuid,tenant_id,business_id,provider_type,legal_name,description,phone,email,address,city,district,state,postal_code,latitude,longitude,status,created_by,updated_by) VALUES(UUID(),?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",[$t,$bid,$d['provider_type'],$d['legal_name'],$d['description'],$d['phone'],$d['email'],$d['address'],$d['city'],$d['district'],$d['state'],$d['postal_code'],$d['latitude'],$d['longitude'],$d['status'],$u,$u]);return (int)$this->db->lastInsertId();}
 public function update(int $t,int $id,array $d,int $u):void{$r=$this->find($t,$id);if(!$r)return;$this->db->execute("UPDATE businesses SET name=?,slug=?,phone=?,email=?,address=?,city=?,district=?,state=?,postal_code=?,status=?,updated_by=? WHERE tenant_id=? AND id=? AND deleted_at IS NULL",[$d['business_name'],$d['business_slug'],$d['phone'],$d['email'],$d['address'],$d['city'],$d['district'],$d['state'],$d['postal_code'],$d['status'],$u,$t,(int)$r['business_id']]);$this->db->execute("UPDATE tourism_providers SET provider_type=?,legal_name=?,description=?,phone=?,email=?,address=?,city=?,district=?,state=?,postal_code=?,latitude=?,longitude=?,status=?,updated_by=? WHERE tenant_id=? AND id=? AND deleted_at IS NULL",[$d['provider_type'],$d['legal_name'],$d['description'],$d['phone'],$d['email'],$d['address'],$d['city'],$d['district'],$d['state'],$d['postal_code'],$d['latitude'],$d['longitude'],$d['status'],$u,$t,$id]);}
 public function softDelete(int $t,int $id,int $u):void{$r=$this->find($t,$id);if(!$r)return;$this->db->execute("UPDATE tourism_providers SET deleted_at=NOW(),updated_by=? WHERE tenant_id=? AND id=? AND deleted_at IS NULL",[$u,$t,$id]);$this->db->execute("UPDATE businesses SET deleted_at=NOW(),updated_by=? WHERE tenant_id=? AND id=? AND deleted_at IS NULL",[$u,$t,(int)$r['business_id']]);}
 public function restore(int $t,int $id,int $u):void{$r=$this->findDeleted($t,$id);if(!$r)return;$this->db->execute("UPDATE businesses SET deleted_at=NULL,updated_by=? WHERE tenant_id=? AND id=?",[$u,$t,(int)$r['business_id']]);$this->db->execute("UPDATE tourism_providers SET deleted_at=NULL,updated_by=? WHERE tenant_id=? AND id=?",[$u,$t,$id]);}
 public function businessNameExists(int $t,string $name,?int $ignore=null):bool{$sql="SELECT p.id FROM tourism_providers p INNER JOIN businesses b ON b.id=p.business_id AND b.tenant_id=p.tenant_id WHERE p.tenant_id=? AND b.name=? AND p.deleted_at IS NULL AND b.deleted_at IS NULL";$p=[$t,$name];if($ignore!==null){$sql.=" AND p.id<>?";$p[]=$ignore;}return $this->db->fetch($sql.' LIMIT 1',$p)!==null;}
 public function slugExists(int $t,string $slug,?int $ignore=null):bool{$sql="SELECT p.id FROM tourism_providers p INNER JOIN businesses b ON b.id=p.business_id AND b.tenant_id=p.tenant_id WHERE p.tenant_id=? AND b.slug=? AND p.deleted_at IS NULL AND b.deleted_at IS NULL";$p=[$t,$slug];if($ignore!==null){$sql.=" AND p.id<>?";$p[]=$ignore;}return $this->db->fetch($sql.' LIMIT 1',$p)!==null;}
}
