<?php
declare(strict_types=1);
namespace App\Modules\Tourism\Models;
use App\Core\Database;
final class TourismPackage {
 private Database $db; public function __construct(){ $this->db=app()->get('db'); }
 public function all(int $t,bool $deleted=false):array{$w=$deleted?'p.deleted_at IS NOT NULL':'p.deleted_at IS NULL';return $this->db->fetchAll("SELECT p.*,tp.legal_name provider_name,(SELECT COUNT(*) FROM tourism_package_destinations pd WHERE pd.package_id=p.id) destination_count FROM tourism_packages p LEFT JOIN tourism_providers tp ON tp.id=p.provider_id AND tp.tenant_id=p.tenant_id WHERE p.tenant_id=? AND {$w} ORDER BY p.id DESC",[$t]);}
 public function find(int $t,int $id,bool $deleted=false):?array{$w=$deleted?'p.deleted_at IS NOT NULL':'p.deleted_at IS NULL';return $this->db->fetch("SELECT p.*,tp.legal_name provider_name FROM tourism_packages p LEFT JOIN tourism_providers tp ON tp.id=p.provider_id AND tp.tenant_id=p.tenant_id WHERE p.tenant_id=? AND p.id=? AND {$w} LIMIT 1",[$t,$id]);}
 public function destinations(int $t,int $id):array{return $this->db->fetchAll("SELECT pd.*,d.name,d.slug,d.district,d.city,d.latitude,d.longitude FROM tourism_package_destinations pd INNER JOIN tourism_destinations d ON d.id=pd.destination_id AND d.tenant_id=pd.tenant_id WHERE pd.tenant_id=? AND pd.package_id=? ORDER BY pd.day_number,pd.sequence_no,pd.id",[$t,$id]);}
 public function providers(int $t):array{return $this->db->fetchAll("SELECT id,legal_name,provider_type FROM tourism_providers WHERE tenant_id=? AND deleted_at IS NULL AND status='Active' ORDER BY legal_name",[$t]);}
 public function destinationsForSelect(int $t):array{return $this->db->fetchAll("SELECT id,name,district,city FROM tourism_destinations WHERE tenant_id=? AND deleted_at IS NULL AND status='Active' ORDER BY name",[$t]);}
 public function create(int $t,array $d,int $u):int{$this->db->execute("INSERT INTO tourism_packages(uuid,tenant_id,provider_id,title,slug,description,duration_days,duration_nights,pricing_type,base_price,discount_price,max_travellers,cover_image_path,status,created_by,updated_by) VALUES(UUID(),?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",[$t,$d['provider_id'],$d['title'],$d['slug'],$d['description'],$d['duration_days'],$d['duration_nights'],$d['pricing_type'],$d['base_price'],$d['discount_price'],$d['max_travellers'],$d['cover_image_path'],$d['status'],$u,$u]);return (int)$this->db->lastInsertId();}
 public function update(int $t,int $id,array $d,int $u):void{$this->db->execute("UPDATE tourism_packages SET provider_id=?,title=?,slug=?,description=?,duration_days=?,duration_nights=?,pricing_type=?,base_price=?,discount_price=?,max_travellers=?,cover_image_path=?,status=?,updated_by=? WHERE tenant_id=? AND id=? AND deleted_at IS NULL",[$d['provider_id'],$d['title'],$d['slug'],$d['description'],$d['duration_days'],$d['duration_nights'],$d['pricing_type'],$d['base_price'],$d['discount_price'],$d['max_travellers'],$d['cover_image_path'],$d['status'],$u,$t,$id]);}
 public function addDestination(int $t,int $packageId,int $destinationId,int $day,int $seq,?string $notes):void{$this->db->execute("INSERT INTO tourism_package_destinations(uuid,tenant_id,package_id,destination_id,day_number,sequence_no,notes) VALUES(UUID(),?,?,?,?,?,?)",[$t,$packageId,$destinationId,$day,$seq,$notes]);}
 public function removeDestination(int $t,int $packageId,int $relationId):void{$this->db->execute("DELETE FROM tourism_package_destinations WHERE tenant_id=? AND package_id=? AND id=?",[$t,$packageId,$relationId]);}
 public function softDelete(int $t,int $id,int $u):void{$this->db->execute("UPDATE tourism_packages SET deleted_at=NOW(),updated_by=? WHERE tenant_id=? AND id=? AND deleted_at IS NULL",[$u,$t,$id]);}
 public function restore(int $t,int $id,int $u):void{$this->db->execute("UPDATE tourism_packages SET deleted_at=NULL,updated_by=? WHERE tenant_id=? AND id=?",[$u,$t,$id]);}
 public function nameExists(int $t,string $name,?int $ignore=null):bool{$sql="SELECT id FROM tourism_packages WHERE tenant_id=? AND title=? AND deleted_at IS NULL";$p=[$t,$name];if($ignore!==null){$sql.=" AND id<>?";$p[]=$ignore;}return $this->db->fetch($sql.' LIMIT 1',$p)!==null;}
 public function slugExists(int $t,string $slug,?int $ignore=null):bool{$sql="SELECT id FROM tourism_packages WHERE tenant_id=? AND slug=? AND deleted_at IS NULL";$p=[$t,$slug];if($ignore!==null){$sql.=" AND id<>?";$p[]=$ignore;}return $this->db->fetch($sql.' LIMIT 1',$p)!==null;}
}
