<?php
declare(strict_types=1);
namespace App\Modules\FreshFood\Models;
use App\Core\Database;
final class FreshFood {
 private Database $db; public function __construct(){ $this->db=app()->get('db'); }
 public function all(int $tenantId,bool $deleted=false):array { $where=$deleted?'p.deleted_at IS NOT NULL AND b.deleted_at IS NOT NULL':'p.deleted_at IS NULL AND b.deleted_at IS NULL'; return $this->db->fetchAll("SELECT p.*,b.name business_name,b.slug business_slug,b.phone,b.email,b.address,b.city,b.district,b.state,b.postal_code,b.status business_status,(SELECT COUNT(*) FROM fresh_food_categories c WHERE c.fresh_food_id=p.id AND c.deleted_at IS NULL) category_count,(SELECT COUNT(*) FROM fresh_food_products f WHERE f.fresh_food_id=p.id AND f.deleted_at IS NULL) product_count FROM fresh_food_profiles p INNER JOIN businesses b ON b.id=p.business_id AND b.tenant_id=p.tenant_id WHERE p.tenant_id=? AND {$where} ORDER BY p.id DESC",[$tenantId]); }
 public function find(int $tenantId,int $id):?array { return $this->db->fetch("SELECT p.*,b.name business_name,b.slug business_slug,b.phone,b.email,b.address,b.city,b.district,b.state,b.postal_code,b.status business_status FROM fresh_food_profiles p INNER JOIN businesses b ON b.id=p.business_id AND b.tenant_id=p.tenant_id WHERE p.tenant_id=? AND p.id=? AND p.deleted_at IS NULL AND b.deleted_at IS NULL LIMIT 1",[$tenantId,$id]); }
 public function findDeleted(int $tenantId,int $id):?array { return $this->db->fetch("SELECT p.*,b.name business_name,b.slug business_slug,b.phone,b.email,b.address,b.city,b.district,b.state,b.postal_code,b.status business_status FROM fresh_food_profiles p INNER JOIN businesses b ON b.id=p.business_id AND b.tenant_id=p.tenant_id WHERE p.tenant_id=? AND p.id=? AND p.deleted_at IS NOT NULL AND b.deleted_at IS NOT NULL LIMIT 1",[$tenantId,$id]); }
 public function nameExists(int $tenantId,string $name,?int $ignore=null):bool { $sql="SELECT p.id FROM fresh_food_profiles p JOIN businesses b ON b.id=p.business_id WHERE p.tenant_id=? AND b.name=? AND b.business_type='fresh_food' AND p.deleted_at IS NULL AND b.deleted_at IS NULL";$p=[$tenantId,$name]; if($ignore!==null){$sql.=" AND p.id<>?";$p[]=$ignore;} return $this->db->fetch($sql.' LIMIT 1',$p)!==null; }
 public function slugExists(int $tenantId,string $slug,?int $ignore=null):bool { $sql="SELECT p.id FROM fresh_food_profiles p JOIN businesses b ON b.id=p.business_id WHERE p.tenant_id=? AND b.slug=? AND b.business_type='fresh_food' AND p.deleted_at IS NULL AND b.deleted_at IS NULL";$p=[$tenantId,$slug]; if($ignore!==null){$sql.=" AND p.id<>?";$p[]=$ignore;} return $this->db->fetch($sql.' LIMIT 1',$p)!==null; }
 public function create(int $tenantId,array $d,int $uid):int { $this->db->execute("INSERT INTO businesses (uuid,tenant_id,name,slug,business_type,phone,email,address,city,district,state,postal_code,status,created_by,updated_by) VALUES(UUID(),?,?,?,?,?,?,?,?,?,?,?,?,?,?)",[$tenantId,$d['business_name'],$d['business_slug'],'fresh_food',$d['phone'],$d['email'],$d['address'],$d['city'],$d['district'],$d['state'],$d['postal_code'],$d['status'],$uid,$uid]); $bid=(int)$this->db->lastInsertId(); $this->db->execute("INSERT INTO fresh_food_profiles (uuid,tenant_id,business_id,description,latitude,longitude,delivery_available,pickup_available,max_delivery_distance_km,minimum_delivery_fee,included_delivery_distance_km,additional_delivery_fee_per_km,preorder_enabled,preorder_min_advance_hours,preorder_delivery_fee,estimated_packing_minutes_min,estimated_packing_minutes_max,accepting_orders,status,created_by,updated_by) VALUES(UUID(),?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",[$tenantId,$bid,$d['description'],$d['latitude'],$d['longitude'],$d['delivery_available'],$d['pickup_available'],$d['max_delivery_distance_km'],$d['minimum_delivery_fee'],$d['included_delivery_distance_km'],$d['additional_delivery_fee_per_km'],$d['preorder_enabled'],$d['preorder_min_advance_hours'],$d['preorder_delivery_fee'],$d['estimated_packing_minutes_min'],$d['estimated_packing_minutes_max'],$d['accepting_orders'],$d['status'],$uid,$uid]); return (int)$this->db->lastInsertId(); }
 public function update(int $tenantId,int $id,array $d,int $uid):void { $r=$this->find($tenantId,$id); if(!$r)return; $this->db->execute("UPDATE businesses SET name=?,slug=?,phone=?,email=?,address=?,city=?,district=?,state=?,postal_code=?,status=?,updated_by=? WHERE tenant_id=? AND id=? AND deleted_at IS NULL",[$d['business_name'],$d['business_slug'],$d['phone'],$d['email'],$d['address'],$d['city'],$d['district'],$d['state'],$d['postal_code'],$d['status'],$uid,$tenantId,(int)$r['business_id']]); $this->db->execute("UPDATE fresh_food_profiles SET description=?,latitude=?,longitude=?,delivery_available=?,pickup_available=?,max_delivery_distance_km=?,minimum_delivery_fee=?,included_delivery_distance_km=?,additional_delivery_fee_per_km=?,preorder_enabled=?,preorder_min_advance_hours=?,preorder_delivery_fee=?,estimated_packing_minutes_min=?,estimated_packing_minutes_max=?,accepting_orders=?,status=?,updated_by=? WHERE tenant_id=? AND id=? AND deleted_at IS NULL",[$d['description'],$d['latitude'],$d['longitude'],$d['delivery_available'],$d['pickup_available'],$d['max_delivery_distance_km'],$d['minimum_delivery_fee'],$d['included_delivery_distance_km'],$d['additional_delivery_fee_per_km'],$d['preorder_enabled'],$d['preorder_min_advance_hours'],$d['preorder_delivery_fee'],$d['estimated_packing_minutes_min'],$d['estimated_packing_minutes_max'],$d['accepting_orders'],$d['status'],$uid,$tenantId,$id]); }
 public function softDelete(int $tenantId,int $id,int $uid):void{$r=$this->find($tenantId,$id);if(!$r)return;$this->db->execute("UPDATE fresh_food_profiles SET deleted_at=NOW(),updated_by=? WHERE tenant_id=? AND id=? AND deleted_at IS NULL",[$uid,$tenantId,$id]);$this->db->execute("UPDATE businesses SET deleted_at=NOW(),updated_by=? WHERE tenant_id=? AND id=? AND deleted_at IS NULL",[$uid,$tenantId,(int)$r['business_id']]);}
 public function restore(int $tenantId,int $id,int $uid):void{$r=$this->findDeleted($tenantId,$id);if(!$r)return;$this->db->execute("UPDATE businesses SET deleted_at=NULL,updated_by=? WHERE tenant_id=? AND id=?",[$uid,$tenantId,(int)$r['business_id']]);$this->db->execute("UPDATE fresh_food_profiles SET deleted_at=NULL,updated_by=? WHERE tenant_id=? AND id=?",[$uid,$tenantId,$id]);}
 public function hours(int $tenantId,int $id):array{return $this->db->fetchAll("SELECT * FROM fresh_food_hours WHERE tenant_id=? AND fresh_food_id=? ORDER BY day_of_week",[$tenantId,$id]);}
 public function replaceHours(int $tenantId,int $id,array $hours):void{$this->db->execute("DELETE FROM fresh_food_hours WHERE tenant_id=? AND fresh_food_id=?",[$tenantId,$id]);foreach($hours as $day=>$h){$this->db->execute("INSERT INTO fresh_food_hours(uuid,tenant_id,fresh_food_id,day_of_week,opens_at,closes_at,is_closed,created_by,updated_by) VALUES(UUID(),?,?,?,?,?,?,?,?)",[$tenantId,$id,$day,$h['opens_at'],$h['closes_at'],$h['is_closed'],$h['created_by'],$h['updated_by']]);}}
 public function dashboard(int $tenantId):array{$r=$this->db->fetch("SELECT COUNT(*) total,SUM(status='Active' AND deleted_at IS NULL) active,SUM(deleted_at IS NOT NULL) deleted FROM fresh_food_profiles WHERE tenant_id=?",[$tenantId])??[];return ['total'=>(int)($r['total']??0),'active'=>(int)($r['active']??0),'deleted'=>(int)($r['deleted']??0)];}
}
