<?php
declare(strict_types=1);
use App\Modules\FreshFood\Controllers\FreshFoodController;
use App\Modules\FreshFood\Controllers\FreshFoodCategoryController;
use App\Modules\FreshFood\Controllers\FreshFoodProductController;
use App\Modules\FreshFood\Controllers\FreshFoodInventoryController;
use App\Modules\FreshFood\Controllers\FreshFoodOrderController;
use App\Modules\FreshFood\Controllers\FreshFoodCouponController;
$router->get('/fresh-food',[FreshFoodController::class,'index'],['auth']);
$router->get('/fresh-food/businesses',[FreshFoodController::class,'businesses'],['auth']);
$router->get('/fresh-food/businesses/create',[FreshFoodController::class,'create'],['auth']);
$router->post('/fresh-food/businesses',[FreshFoodController::class,'store'],['auth']);
$router->get('/fresh-food/businesses/{id}',[FreshFoodController::class,'show'],['auth']);
$router->get('/fresh-food/businesses/{id}/edit',[FreshFoodController::class,'edit'],['auth']);
$router->post('/fresh-food/businesses/{id}',[FreshFoodController::class,'update'],['auth']);
$router->post('/fresh-food/businesses/{id}/hours',[FreshFoodController::class,'hours'],['auth']);
$router->post('/fresh-food/businesses/{id}/delete',[FreshFoodController::class,'destroy'],['auth']);
$router->post('/fresh-food/businesses/{id}/restore',[FreshFoodController::class,'restore'],['auth']);
$router->get('/fresh-food/categories',[FreshFoodCategoryController::class,'index'],['auth']);
$router->get('/fresh-food/categories/create',[FreshFoodCategoryController::class,'create'],['auth']);
$router->post('/fresh-food/categories',[FreshFoodCategoryController::class,'store'],['auth']);
$router->get('/fresh-food/categories/{id}/edit',[FreshFoodCategoryController::class,'edit'],['auth']);
$router->post('/fresh-food/categories/{id}',[FreshFoodCategoryController::class,'update'],['auth']);
$router->post('/fresh-food/categories/{id}/delete',[FreshFoodCategoryController::class,'destroy'],['auth']);
$router->post('/fresh-food/categories/{id}/restore',[FreshFoodCategoryController::class,'restore'],['auth']);
$router->get('/fresh-food/products',[FreshFoodProductController::class,'index'],['auth']);
$router->get('/fresh-food/products/create',[FreshFoodProductController::class,'create'],['auth']);
$router->get('/fresh-food/products/categories/{freshFoodId}',[FreshFoodProductController::class,'categories'],['auth']);
$router->post('/fresh-food/products',[FreshFoodProductController::class,'store'],['auth']);
$router->get('/fresh-food/products/{id}/edit',[FreshFoodProductController::class,'edit'],['auth']);
$router->post('/fresh-food/products/{id}',[FreshFoodProductController::class,'update'],['auth']);
$router->post('/fresh-food/products/{id}/delete',[FreshFoodProductController::class,'destroy'],['auth']);
$router->post('/fresh-food/products/{id}/restore',[FreshFoodProductController::class,'restore'],['auth']);
$router->get('/fresh-food/inventory',[FreshFoodInventoryController::class,'index'],['auth']);
$router->get('/fresh-food/inventory/adjust',[FreshFoodInventoryController::class,'adjust'],['auth']);
$router->post('/fresh-food/inventory/adjust',[FreshFoodInventoryController::class,'storeAdjustment'],['auth']);
$router->get('/fresh-food/inventory/{productId}/movements',[FreshFoodInventoryController::class,'movements'],['auth']);

$router->get('/fresh-food/orders',[FreshFoodOrderController::class,'index'],['auth']);
$router->get('/fresh-food/orders/create',[FreshFoodOrderController::class,'create'],['auth']);
$router->get('/fresh-food/orders/products/{freshFoodId}',[FreshFoodOrderController::class,'products'],['auth']);
$router->get('/fresh-food/orders/coupons/{freshFoodId}',[FreshFoodOrderController::class,'coupons'],['auth']);
$router->get('/fresh-food/orders/coupon-preview/{freshFoodId}',[FreshFoodOrderController::class,'couponPreview'],['auth']);
$router->post('/fresh-food/orders',[FreshFoodOrderController::class,'store'],['auth']);
$router->get('/fresh-food/orders/{id}',[FreshFoodOrderController::class,'show'],['auth']);
$router->post('/fresh-food/orders/{id}/status',[FreshFoodOrderController::class,'transition'],['auth']);

$router->get('/fresh-food/coupons',[FreshFoodCouponController::class,'index'],['auth']);
$router->get('/fresh-food/coupons/create',[FreshFoodCouponController::class,'create'],['auth']);
$router->post('/fresh-food/coupons',[FreshFoodCouponController::class,'store'],['auth']);
$router->get('/fresh-food/coupons/{id}/edit',[FreshFoodCouponController::class,'edit'],['auth']);
$router->post('/fresh-food/coupons/{id}',[FreshFoodCouponController::class,'update'],['auth']);
$router->post('/fresh-food/coupons/{id}/delete',[FreshFoodCouponController::class,'destroy'],['auth']);
