SET NAMES utf8mb4;
START TRANSACTION;

CREATE TABLE IF NOT EXISTS commercial_rental_providers (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid CHAR(36) NOT NULL,
    tenant_id BIGINT UNSIGNED NOT NULL,
    business_id BIGINT UNSIGNED NOT NULL,
    legal_name VARCHAR(255) DEFAULT NULL,
    description TEXT DEFAULT NULL,
    phone VARCHAR(30) DEFAULT NULL,
    email VARCHAR(255) DEFAULT NULL,
    address VARCHAR(500) DEFAULT NULL,
    city VARCHAR(150) DEFAULT NULL,
    district VARCHAR(150) DEFAULT NULL,
    state VARCHAR(150) DEFAULT 'Manipur',
    postal_code VARCHAR(20) DEFAULT NULL,
    latitude DECIMAL(10,7) DEFAULT NULL,
    longitude DECIMAL(10,7) DEFAULT NULL,
    service_areas TEXT DEFAULT NULL,
    status ENUM('Active','Inactive','Suspended') NOT NULL DEFAULT 'Active',
    created_by BIGINT UNSIGNED DEFAULT NULL,
    updated_by BIGINT UNSIGNED DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_cr_provider_uuid (uuid),
    UNIQUE KEY uq_cr_provider_business (tenant_id,business_id),
    KEY idx_cr_provider_location (tenant_id,latitude,longitude),
    KEY idx_cr_provider_district (tenant_id,district),
    KEY idx_cr_provider_status (tenant_id,status),
    KEY idx_cr_provider_deleted (tenant_id,deleted_at),
    CONSTRAINT fk_cr_provider_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_cr_provider_business FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE,
    CONSTRAINT fk_cr_provider_created FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_cr_provider_updated FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS commercial_rental_categories (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid CHAR(36) NOT NULL,
    tenant_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(150) NOT NULL,
    slug VARCHAR(180) NOT NULL,
    description TEXT DEFAULT NULL,
    status ENUM('Active','Inactive') NOT NULL DEFAULT 'Active',
    created_by BIGINT UNSIGNED DEFAULT NULL,
    updated_by BIGINT UNSIGNED DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY(id),
    UNIQUE KEY uq_cr_category_uuid(uuid),
    UNIQUE KEY uq_cr_category_slug(tenant_id,slug),
    KEY idx_cr_category_status(tenant_id,status),
    CONSTRAINT fk_cr_category_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_cr_category_created FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_cr_category_updated FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS commercial_rental_vehicles (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid CHAR(36) NOT NULL,
    tenant_id BIGINT UNSIGNED NOT NULL,
    provider_id BIGINT UNSIGNED NOT NULL,
    category_id BIGINT UNSIGNED DEFAULT NULL,
    name VARCHAR(180) NOT NULL,
    make VARCHAR(100) DEFAULT NULL,
    model VARCHAR(100) DEFAULT NULL,
    model_year SMALLINT UNSIGNED DEFAULT NULL,
    registration_no VARCHAR(50) DEFAULT NULL,
    capacity VARCHAR(100) DEFAULT NULL,
    operator_included TINYINT(1) NOT NULL DEFAULT 0,
    rate_type ENUM('FIXED','HOURLY','DAILY','PER_TRIP','CUSTOM_QUOTE') NOT NULL DEFAULT 'CUSTOM_QUOTE',
    rate DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    minimum_rental DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    description TEXT DEFAULT NULL,
    photo_path VARCHAR(500) DEFAULT NULL,
    status ENUM('Active','Inactive','Maintenance') NOT NULL DEFAULT 'Active',
    availability ENUM('Available','Booked','Unavailable') NOT NULL DEFAULT 'Available',
    created_by BIGINT UNSIGNED DEFAULT NULL,
    updated_by BIGINT UNSIGNED DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY(id),
    UNIQUE KEY uq_cr_vehicle_uuid(uuid),
    UNIQUE KEY uq_cr_vehicle_registration(tenant_id,registration_no),
    KEY idx_cr_vehicle_provider(tenant_id,provider_id),
    KEY idx_cr_vehicle_category(tenant_id,category_id),
    KEY idx_cr_vehicle_status(tenant_id,status),
    KEY idx_cr_vehicle_availability(tenant_id,availability),
    CONSTRAINT fk_cr_vehicle_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_cr_vehicle_provider FOREIGN KEY (provider_id) REFERENCES commercial_rental_providers(id) ON DELETE CASCADE,
    CONSTRAINT fk_cr_vehicle_category FOREIGN KEY (category_id) REFERENCES commercial_rental_categories(id) ON DELETE SET NULL,
    CONSTRAINT fk_cr_vehicle_created FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_cr_vehicle_updated FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS commercial_rental_requests (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid CHAR(36) NOT NULL,
    tenant_id BIGINT UNSIGNED NOT NULL,
    member_id BIGINT UNSIGNED DEFAULT NULL,
    provider_id BIGINT UNSIGNED DEFAULT NULL,
    vehicle_id BIGINT UNSIGNED DEFAULT NULL,
    request_no VARCHAR(50) NOT NULL,
    customer_name VARCHAR(150) NOT NULL,
    customer_phone VARCHAR(30) NOT NULL,
    purpose VARCHAR(255) DEFAULT NULL,
    pickup_address VARCHAR(500) NOT NULL,
    pickup_lat DECIMAL(10,7) DEFAULT NULL,
    pickup_lng DECIMAL(10,7) DEFAULT NULL,
    destination_address VARCHAR(500) DEFAULT NULL,
    destination_lat DECIMAL(10,7) DEFAULT NULL,
    destination_lng DECIMAL(10,7) DEFAULT NULL,
    start_at DATETIME DEFAULT NULL,
    end_at DATETIME DEFAULT NULL,
    duration_text VARCHAR(100) DEFAULT NULL,
    operator_required TINYINT(1) NOT NULL DEFAULT 0,
    status ENUM('REQUESTED','CONTACTING','QUOTED','CONFIRMED','IN_PROGRESS','COMPLETED','CANCELLED','REJECTED') NOT NULL DEFAULT 'REQUESTED',
    quoted_amount DECIMAL(12,2) DEFAULT NULL,
    final_amount DECIMAL(12,2) DEFAULT NULL,
    customer_notes TEXT DEFAULT NULL,
    admin_notes TEXT DEFAULT NULL,
    created_by BIGINT UNSIGNED DEFAULT NULL,
    updated_by BIGINT UNSIGNED DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY(id),
    UNIQUE KEY uq_cr_request_uuid(uuid),
    UNIQUE KEY uq_cr_request_no(tenant_id,request_no),
    KEY idx_cr_request_member(tenant_id,member_id),
    KEY idx_cr_request_provider(tenant_id,provider_id),
    KEY idx_cr_request_vehicle(tenant_id,vehicle_id),
    KEY idx_cr_request_status(tenant_id,status),
    KEY idx_cr_request_pickup(tenant_id,pickup_lat,pickup_lng),
    CONSTRAINT fk_cr_request_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_cr_request_member FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE SET NULL,
    CONSTRAINT fk_cr_request_provider FOREIGN KEY (provider_id) REFERENCES commercial_rental_providers(id) ON DELETE SET NULL,
    CONSTRAINT fk_cr_request_vehicle FOREIGN KEY (vehicle_id) REFERENCES commercial_rental_vehicles(id) ON DELETE SET NULL,
    CONSTRAINT fk_cr_request_created FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_cr_request_updated FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

COMMIT;
