<?php declare(strict_types=1);
include __DIR__ . '/../Shared/member-desktop.css.php';
include __DIR__ . '/../Shared/member-desktop-header.php';
 $basePath=rtrim((string)config('app.base_path'),'/'); $p=is_array($profile??null)?$profile:[]; function maPe(mixed $v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');} ?>
<style>
.ma-profile{max-width:560px;margin:auto;padding:16px 16px 110px;color:#14251f}.ma-profile *{box-sizing:border-box}.mp-head{display:flex;align-items:center;gap:12px}.mp-head a{font-size:28px;text-decoration:none;color:#173c32}.mp-head h1{margin:0;font-size:25px}.mp-head p{margin:3px 0;color:#74827d;font-size:12px}.mp-card{background:#fff;border:1px solid #e2ece8;border-radius:22px;padding:20px;margin-top:18px;box-shadow:0 8px 24px rgba(15,60,45,.06)}.mp-avatar{width:74px;height:74px;border-radius:50%;background:#dff3eb;color:#087d64;display:grid;place-items:center;font-size:30px;font-weight:900;margin-bottom:14px}.mp-name{font-size:22px;font-weight:900}.mp-no{color:#75847e;font-size:12px;margin-top:3px}.mp-row{display:flex;justify-content:space-between;gap:15px;padding:14px 0;border-bottom:1px solid #edf2f0;font-size:13px}.mp-row:last-child{border-bottom:0}.mp-row span{color:#75847e}.mp-row b{text-align:right}.mp-actions{display:grid;gap:10px;margin-top:16px}.mp-btn{display:block;text-align:center;text-decoration:none;border-radius:14px;padding:14px;font-weight:800}.mp-primary{background:#087d64;color:#fff}.mp-light{background:#f0f6f3;color:#126c59}.mp-danger{background:#fff1f1;color:#a33b3b}.mp-nav{position:fixed;left:50%;bottom:10px;transform:translateX(-50%);width:min(540px,calc(100% - 20px));background:rgba(255,255,255,.96);border:1px solid #e1ebe7;box-shadow:0 10px 30px rgba(0,0,0,.12);border-radius:22px;display:grid;grid-template-columns:repeat(4,1fr);padding:7px;z-index:30}.mp-nav a{text-decoration:none;color:#73827c;text-align:center;padding:8px 3px;font-size:11px;font-weight:700}.mp-nav a.active{color:#087d64}.mp-nav i{display:block;font-style:normal;font-size:20px;margin-bottom:2px}
</style>
<div class="ma-profile"><header class="mp-head"><a href="<?=maPe($basePath)?>/member">‹</a><div><h1>Profile</h1><p>Your ManipurApp account</p></div></header><section class="mp-card"><div class="mp-avatar"><?=maPe(strtoupper(substr((string)($p['first_name']??'M'),0,1)))?></div><div class="mp-name"><?=maPe(trim(($p['first_name']??'').' '.($p['last_name']??'')))?></div><div class="mp-no">Member #<?=maPe($p['member_no']??'-')?></div><div class="mp-row"><span>Phone</span><b><?=maPe($p['phone']??'-')?></b></div><div class="mp-row"><span>Email</span><b><?=maPe($p['email']??'-')?></b></div><div class="mp-row"><span>Status</span><b><?=maPe($p['status']??'-')?></b></div><div class="mp-actions"><a class="mp-btn mp-primary" href="<?=maPe($basePath)?>/member/bookings">My Bookings</a><a class="mp-btn mp-light" href="<?=maPe($basePath)?>/member/taxi">Book a Taxi</a><a class="mp-btn mp-danger" href="<?=maPe($basePath)?>/member/logout">Log out</a></div></section><?php include __DIR__ . '/../Shared/restaurant-cart-widget.php'; ?>
<?php include __DIR__ . '/../Shared/fresh-food-cart-widget.php'; ?>
<?php include __DIR__ . '/../Shared/member-notification-widget.php'; ?>
</div>
<nav class="mp-nav"><a href="<?=maPe($basePath)?>/member"><i>⌂</i>Home</a><a href="<?=maPe($basePath)?>/member/taxi"><i>🚕</i>Services</a><a href="<?=maPe($basePath)?>/member/bookings"><i>▣</i>Bookings</a><a class="active" href="<?=maPe($basePath)?>/member/profile"><i>♙</i>Profile</a></nav>
<?php include __DIR__ . '/../Shared/member-desktop-footer.php'; ?>
