<?php declare(strict_types=1); $base=config('app.base_path'); $r=$old??[]; ?>
<div class="page-header"><div><h1>Create Fresh Food Order</h1><p>Admin test order with product discounts, coupons and inventory-aware totals.</p></div><div class="page-actions"><a class="btn btn-secondary" href="<?= $base ?>/fresh-food/orders">Orders</a></div></div>
<?php if(!empty($error)): ?><div class="card error-box"><?= htmlspecialchars((string)$error,ENT_QUOTES,'UTF-8') ?></div><?php endif; ?>
<form method="post" action="<?= $base ?>/fresh-food/orders" id="order-form">
<div class="card"><div class="form-grid">
<div class="form-group"><label>Fresh Food Business *</label><select id="business" name="fresh_food_id" required><option value="">Select business</option><?php foreach(($businesses??[]) as $b): ?><option value="<?= (int)$b['id'] ?>" <?= (int)($r['fresh_food_id']??0)===(int)$b['id']?'selected':'' ?>><?= htmlspecialchars((string)$b['business_name'],ENT_QUOTES,'UTF-8') ?></option><?php endforeach; ?></select></div>
<div class="form-group"><label>Order Type *</label><select name="order_type" id="order-type"><option value="DELIVERY" <?= ($r['order_type']??'DELIVERY')==='DELIVERY'?'selected':'' ?>>Delivery</option><option value="PICKUP" <?= ($r['order_type']??'')==='PICKUP'?'selected':'' ?>>Pickup</option></select></div>
<div class="form-group"><label>Member</label><select name="member_id" id="member"><option value="">Walk-in / no member</option><?php foreach(($members??[]) as $m): $mn=$m['preferred_name']?:trim($m['first_name'].' '.($m['last_name']??'')); ?><option value="<?= (int)$m['id'] ?>" data-name="<?= htmlspecialchars($mn,ENT_QUOTES,'UTF-8') ?>" data-phone="<?= htmlspecialchars((string)($m['phone']??''),ENT_QUOTES,'UTF-8') ?>" data-email="<?= htmlspecialchars((string)($m['email']??''),ENT_QUOTES,'UTF-8') ?>" <?= (int)($r['member_id']??0)===(int)$m['id']?'selected':'' ?>><?= htmlspecialchars($mn,ENT_QUOTES,'UTF-8') ?><?= !empty($m['phone'])?' — '.htmlspecialchars($m['phone'],ENT_QUOTES,'UTF-8'):'' ?></option><?php endforeach; ?></select></div>
<div class="form-group"><label>Customer Name *</label><input id="customer-name" name="customer_name" required value="<?= htmlspecialchars((string)($r['customer_name']??''),ENT_QUOTES,'UTF-8') ?>"></div>
<div class="form-group"><label>Phone</label><input id="customer-phone" name="customer_phone" value="<?= htmlspecialchars((string)($r['customer_phone']??''),ENT_QUOTES,'UTF-8') ?>"></div>
<div class="form-group"><label>Email</label><input id="customer-email" name="customer_email" value="<?= htmlspecialchars((string)($r['customer_email']??''),ENT_QUOTES,'UTF-8') ?>"></div>
</div></div>
<div class="card"><h2>Products</h2><div id="product-rows"></div><button class="btn btn-secondary" type="button" id="add-row">+ Add Product</button><div class="totals"><strong>Gross Subtotal: ₹<span id="gross-subtotal">0.00</span></strong><br>Item Discounts: ₹<span id="item-discount">0.00</span><br>Net Items: ₹<span id="net-subtotal">0.00</span></div></div>
<div class="card"><h2>Discount & Delivery</h2><div class="form-grid">
<div class="form-group"><label>Coupon</label><select name="coupon_code" id="coupon"><option value="">No coupon</option></select><small id="coupon-message">Select a business to load active coupons.</small></div>
<div class="form-group"><label>Manual Order Discount</label><input type="number" step="0.01" min="0" name="discount" id="manual-discount" value="<?= htmlspecialchars((string)($r['discount']??'0'),ENT_QUOTES,'UTF-8') ?>"><small>This is an additional admin-only order discount.</small></div>
<div class="form-group delivery-only"><label>Delivery Fee</label><input type="number" step="0.01" min="0" name="delivery_fee" id="delivery-fee" value="<?= htmlspecialchars((string)($r['delivery_fee']??'30'),ENT_QUOTES,'UTF-8') ?>"></div>
<div class="form-group"><label>Payment Method</label><select name="payment_method"><option value="">Not paid / pending</option><option>CASH</option><option>UPI</option><option>CARD</option></select></div>
<div class="form-group delivery-only full-width"><label>Address *</label><textarea name="delivery_address" id="delivery-address" rows="3"><?= htmlspecialchars((string)($r['delivery_address']??''),ENT_QUOTES,'UTF-8') ?></textarea></div>
<div class="form-group delivery-only"><label>City</label><input name="delivery_city" value="<?= htmlspecialchars((string)($r['delivery_city']??''),ENT_QUOTES,'UTF-8') ?>"></div><div class="form-group delivery-only"><label>District</label><input name="delivery_district" value="<?= htmlspecialchars((string)($r['delivery_district']??'Imphal West'),ENT_QUOTES,'UTF-8') ?>"></div><div class="form-group delivery-only"><label>State</label><input name="delivery_state" value="<?= htmlspecialchars((string)($r['delivery_state']??'Manipur'),ENT_QUOTES,'UTF-8') ?>"></div><div class="form-group delivery-only"><label>Postal Code</label><input name="delivery_postal_code" value="<?= htmlspecialchars((string)($r['delivery_postal_code']??''),ENT_QUOTES,'UTF-8') ?>"></div>
<div class="form-group full-width"><label>Customer Note</label><textarea name="customer_note" rows="3"><?= htmlspecialchars((string)($r['customer_note']??''),ENT_QUOTES,'UTF-8') ?></textarea></div>
</div><div class="order-total"><span>Coupon Discount: ₹<strong id="coupon-discount">0.00</strong></span><span>Manual Discount: ₹<strong id="manual-discount-display">0.00</strong></span><span>Delivery: ₹<strong id="delivery-display">0.00</strong></span><span class="grand">Grand Total: ₹<strong id="grand-total">0.00</strong></span></div><div class="page-actions"><button class="btn btn-primary" type="submit">Create Order</button><a class="btn btn-secondary" href="<?= $base ?>/fresh-food/orders">Cancel</a></div></div></form>
<style>.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.full-width{grid-column:1/-1}.form-group label{display:block;font-weight:600;margin-bottom:7px}.form-group input,.form-group select,.form-group textarea{width:100%;box-sizing:border-box}.form-group small{display:block;margin-top:5px;opacity:.7}.product-row{display:grid;grid-template-columns:2fr 1fr 1fr 1fr 40px;gap:10px;margin-bottom:10px;align-items:end}.product-row label{font-size:12px;font-weight:600}.remove{height:38px}.totals{text-align:right;margin-top:16px;line-height:1.8}.order-total{text-align:right;margin-top:18px;line-height:1.9}.order-total span{display:block}.order-total .grand{font-size:20px;font-weight:700}.error-box{margin-bottom:16px}@media(max-width:800px){.form-grid{grid-template-columns:1fr}.full-width{grid-column:auto}.product-row{grid-template-columns:1fr 1fr}.product-row .remove{grid-column:2}.order-total{text-align:left}}</style>
<script>
document.addEventListener('DOMContentLoaded',()=>{const base=<?= json_encode($base) ?>,business=document.getElementById('business'),rows=document.getElementById('product-rows'),add=document.getElementById('add-row'),member=document.getElementById('member'),name=document.getElementById('customer-name'),phone=document.getElementById('customer-phone'),email=document.getElementById('customer-email'),type=document.getElementById('order-type'),fee=document.getElementById('delivery-fee'),address=document.getElementById('delivery-address'),coupon=document.getElementById('coupon'),manual=document.getElementById('manual-discount');let products=[];let rowIndex=0;let couponData=[];
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
function updateMember(){const o=member.options[member.selectedIndex];if(!o||!o.value)return;name.value=o.dataset.name||'';phone.value=o.dataset.phone||'';email.value=o.dataset.email||'';}
async function load(){products=[];rows.innerHTML='';coupon.innerHTML='<option value="">Loading coupons...</option>';const f=business.value;if(!f){coupon.innerHTML='<option value="">No coupon</option>';calc();return;}try{const pr=await fetch(base+'/fresh-food/orders/products/'+f,{headers:{Accept:'application/json'}});products=await pr.json();const cr=await fetch(base+'/fresh-food/orders/coupons/'+f,{headers:{Accept:'application/json'}});couponData=await cr.json();coupon.innerHTML='<option value="">No coupon</option>';if(Array.isArray(couponData))couponData.forEach(c=>{const o=document.createElement('option');o.value=c.code;o.textContent=c.code+' — '+c.name+' ('+(c.discount_type==='PERCENT'?Number(c.discount_value).toFixed(2)+'%':'₹'+Number(c.discount_value).toFixed(2))+')';if(c.code===<?= json_encode(strtoupper((string)($r['coupon_code']??''))) ?>)o.selected=true;coupon.appendChild(o)});document.getElementById('coupon-message').textContent=couponData.length?'Select a coupon to apply it to the net item subtotal.':'No active coupons for this business.';addRow();}catch(e){coupon.innerHTML='<option value="">Unable to load coupons</option>';console.error(e)}}
function addRow(){if(!products.length)return;const d=document.createElement('div');d.className='product-row';const idx=rowIndex++;d.innerHTML='<div><label>Product</label><select name="items['+idx+'][product_id]" required><option value="">Select product</option>'+products.map(p=>{const dt=p.discount_type||'NONE',dv=Number(p.discount_value||0),price=Number(p.price||0),disc=dt==='PERCENT'?Math.min(price,price*dv/100):(dt==='FLAT'?Math.min(price,dv):0);return '<option value="'+p.id+'" data-price="'+price+'" data-unit="'+escapeHtml(p.unit)+'" data-discount="'+disc+'">'+escapeHtml(p.name)+' — ₹'+price.toFixed(2)+'/'+escapeHtml(p.unit)+(disc>0?' (sale ₹'+(price-disc).toFixed(2)+')':'')+' — stock '+Number(p.current_quantity).toFixed(3)+'</option>'}).join('')+'</select></div><div><label>Quantity</label><input name="items['+idx+'][quantity]" type="number" min="0.001" step="0.001" value="1" required></div><div><label>Unit Price</label><input class="unit-price" readonly value="₹0.00"></div><div><label>Line Total</label><input class="line-total" readonly value="₹0.00"></div><button type="button" class="btn btn-secondary remove">×</button>';rows.appendChild(d);d.querySelector('select').addEventListener('change',calc);d.querySelector('input[type=number]').addEventListener('input',calc);d.querySelector('.remove').onclick=()=>{d.remove();calc()};calc()}
async function calc(){let gross=0,itemDisc=0;rows.querySelectorAll('.product-row').forEach(r=>{const s=r.querySelector('select'),q=r.querySelector('input[type=number]'),up=r.querySelector('.unit-price'),lt=r.querySelector('.line-total'),o=s.options[s.selectedIndex];const p=o&&o.value?Number(o.dataset.price):0,d=o&&o.value?Number(o.dataset.discount):0,qty=Number(q.value||0),sale=Math.max(0,p-d);up.value='₹'+sale.toFixed(2);lt.value='₹'+(sale*qty).toFixed(2);gross+=p*qty;itemDisc+=d*qty});const net=Math.max(0,gross-itemDisc);let couponDisc=0;const c=couponData.find(x=>x.code===coupon.value);if(c){couponDisc=c.discount_type==='PERCENT'?Math.min(net,net*Number(c.discount_value)/100):Math.min(net,Number(c.discount_value));if(c.maximum_discount!==null)couponDisc=Math.min(couponDisc,Number(c.maximum_discount));if(net<Number(c.minimum_order_amount))couponDisc=0;document.getElementById('coupon-message').textContent=net<Number(c.minimum_order_amount)?'Minimum order for this coupon is ₹'+Number(c.minimum_order_amount).toFixed(2):'Coupon discount: ₹'+couponDisc.toFixed(2)}else document.getElementById('coupon-message').textContent=couponData.length?'Select a coupon to apply it to the net item subtotal.':'No active coupons for this business.';const md=Math.min(Math.max(0,Number(manual.value||0)),Math.max(0,net-couponDisc));const df=type.value==='DELIVERY'?Math.max(0,Number(fee.value||0)):0;document.getElementById('gross-subtotal').textContent=gross.toFixed(2);document.getElementById('item-discount').textContent=itemDisc.toFixed(2);document.getElementById('net-subtotal').textContent=net.toFixed(2);document.getElementById('coupon-discount').textContent=couponDisc.toFixed(2);document.getElementById('manual-discount-display').textContent=md.toFixed(2);document.getElementById('delivery-display').textContent=df.toFixed(2);document.getElementById('grand-total').textContent=Math.max(0,net-couponDisc-md+df).toFixed(2)}
function delivery(){document.querySelectorAll('.delivery-only').forEach(e=>e.style.display=type.value==='DELIVERY'?'block':'none');address.required=type.value==='DELIVERY';if(type.value==='PICKUP')fee.value='0';calc()}
business.onchange=load;add.onclick=addRow;member.onchange=updateMember;type.onchange=delivery;fee.oninput=calc;manual.oninput=calc;coupon.onchange=calc;delivery();if(member.value)updateMember();if(business.value)load();});
</script>
