<?php
declare(strict_types=1);
include __DIR__ . '/../Shared/member-desktop.css.php';
include __DIR__ . '/../Shared/member-desktop-header.php';
$base=rtrim((string)config('app.base_path'),'/');$b=$business??[];$products=is_array($products??null)?$products:[];$cats=is_array($b['categories']??null)?$b['categories']:[];$selected=(int)($selectedCategoryId??0);$csrf=$csrf??'';
function fsEsc(mixed $v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');} function fsRating(mixed $id,string $salt=''):array{$n=abs((int)sprintf('%u',crc32($salt.':'.(string)$id)));return [round(4.5+(($n%5)/10),1),60+($n%297)];} function fsMoney(mixed $v):string{return '₹'.number_format((float)$v,2);}
?>
<style>
.fs-page{max-width:560px;margin:auto;padding:13px 13px 94px;color:#14251f}.fs-head{display:flex;gap:9px;align-items:center}.fs-head a{font-size:27px;text-decoration:none;color:#173c32}.fs-head h1{margin:0;font-size:20px}.fs-head p{margin:2px 0;color:#74827d;font-size:10px}.fs-info{background:#f1f6f3;border-radius:14px;padding:11px;margin:10px 0}.fs-info b{font-size:14px}.fs-info div{font-size:9px;color:#6d7c76;margin-top:3px}.fs-cats{display:flex;gap:6px;overflow:auto;padding:2px 0 8px}.fs-cats a{white-space:nowrap;text-decoration:none;border:1px solid #dce8e3;border-radius:99px;padding:7px 10px;font-size:9px;color:#52665e}.fs-cats a.active{background:#eaf7f2;color:#087d64;border-color:#a9d8ca}.fs-product{display:flex;justify-content:space-between;gap:10px;background:#fff;border:1px solid #e0ebe6;border-radius:14px;padding:11px;margin:7px 0;text-decoration:none;color:inherit}.fs-product b{font-size:12px}.fs-product small{display:block;font-size:9px;color:#71817a;margin-top:3px}.fs-price{text-align:right;font-size:12px;font-weight:950}.fs-old{text-decoration:line-through;color:#87938e;font-size:8px;margin-right:4px}.fs-discount{color:#087d64;font-size:8px;font-weight:900}.fs-sold{color:#a65448;font-size:9px;font-weight:900}.fs-add{display:inline-block;margin-top:5px;background:#087d64;color:#fff;border-radius:8px;padding:6px 9px;font-size:8px;font-weight:900}.fs-nav{position:fixed;left:50%;bottom:6px;transform:translateX(-50%);width:min(540px,calc(100% - 14px));background:#fff;border:1px solid #e1ebe7;box-shadow:0 7px 22px rgba(0,0,0,.1);border-radius:18px;display:grid;grid-template-columns:repeat(4,1fr);padding:4px;z-index:30}.fs-nav a{text-decoration:none;color:#73827c;text-align:center;padding:5px 3px;font-size:9px;font-weight:700}.fs-nav a.active{color:#087d64}.fs-nav i{display:block;font-style:normal;font-size:17px}
</style>
<div class="fs-page"><header class="fs-head"><a href="<?=fsEsc($base)?>/member/fresh-food">‹</a><div><h1><?=fsEsc($b['business_name']??'Fresh Food')?></h1><p><?=!empty($b['is_open'])?'Open now':'Closed now'?> · <?=!empty($b['delivery_available'])?'Delivery':''?><?=(!empty($b['delivery_available'])&&!empty($b['pickup_available']))?' · ':''?><?=!empty($b['pickup_available'])?'Pickup':''?></p></div><a href="<?=fsEsc($base)?>/member/fresh-food/cart">Cart</a></header>
<?php [$storeRating,$storeReviews]=fsRating($b['id']??0,'store'); ?><div class="fs-info"><b>Fresh local products</b><div><?=fsEsc($b['address']??'')?><?=!empty($b['city'])?', '.fsEsc($b['city']):''?></div><div><strong style="color:#eca916">★ <?=number_format($storeRating,1)?></strong> · <?=number_format($storeReviews)?> reviews · <?=!empty($b['accepting_orders'])?'Accepting orders':'Not accepting orders'?> · Delivery radius <?=fsEsc($b['max_delivery_distance_km']??0)?> km</div></div>
<?php if($cats): ?><div class="fs-cats"><a class="<?=$selected===0?'active':''?>" href="<?=fsEsc($base)?>/member/fresh-food/<?=fsEsc($b['id'])?>">All</a><?php foreach($cats as $c): ?><a class="<?=$selected===(int)$c['id']?'active':''?>" href="<?=fsEsc($base)?>/member/fresh-food/<?=fsEsc($b['id'])?>?category_id=<?=fsEsc($c['id'])?>"><?=fsEsc($c['name'])?></a><?php endforeach; ?></div><?php endif; ?>
<?php foreach($products as $p): $price=(float)$p['price'];$display=(float)$p['display_price'];$discount=max(0,$price-$display);$available=!empty($p['is_available'])&&(float)$p['current_quantity']>0;[$productRating,$productReviews]=fsRating($p['id']??0,'product'); ?><a class="fs-product" href="<?=fsEsc($base)?>/member/fresh-food/<?=fsEsc($b['id'])?>/products/<?=fsEsc($p['id'])?>"><div><b><?=fsEsc($p['name'])?></b><small><?=fsEsc($p['category_name']??'')?> · <strong style="color:#eca916">★ <?=number_format($productRating,1)?></strong> (<?=number_format($productReviews)?>)<br>Minimum <?=fsEsc($p['min_order_quantity'])?> <?=fsEsc($p['unit'])?> · Increment <?=fsEsc($p['increment_quantity'])?></small><?php if($available): ?><span class="fs-add">View &amp; Add</span><?php else: ?><span class="fs-sold">Sold out</span><?php endif; ?></div><div class="fs-price"><?php if($discount>0): ?><span class="fs-old"><?=fsMoney($price)?></span><span class="fs-discount"><?=strtoupper((string)$p['discount_type'])==='PERCENT'?fsEsc($p['discount_value']).'% OFF':'₹'.fsEsc($p['discount_value']).' OFF'?></span><br><?php endif; ?><?=fsMoney($display)?> / <?=fsEsc($p['unit'])?></div></a><?php endforeach; ?>
<?php if(!$products): ?><div style="background:#f3f8f5;border-radius:14px;padding:24px;text-align:center;font-size:11px;color:#687a72">No products are available in this category.</div><?php endif; ?>
<?php include __DIR__.'/../Shared/fresh-food-cart-widget.php'; ?><?php include __DIR__.'/../Shared/member-notification-widget.php'; ?></div>
<nav class="fs-nav"><a href="<?=fsEsc($base)?>/member"><i>⌂</i>Home</a><a class="active" href="<?=fsEsc($base)?>/member/fresh-food"><i>🥬</i>Fresh</a><a href="<?=fsEsc($base)?>/member/bookings"><i>▣</i>Bookings</a><a href="<?=fsEsc($base)?>/member/profile"><i>♙</i>Profile</a></nav>
<?php include __DIR__ . '/../Shared/member-desktop-footer.php'; ?>
