<?php
declare(strict_types=1);
namespace App\Modules\Tourism\Services;
use App\Modules\Tourism\Models\TourismGuide;use RuntimeException;use Throwable;
final class TourismGuideService{
 private TourismGuide $m;private TourismImageUploadService $images;public function __construct(){$this->m=new TourismGuide();$this->images=new TourismImageUploadService();}public function all(int $t,bool $d=false):array{return $this->m->all($t,$d);}public function find(int $t,int $id,bool $d=false):?array{return $this->m->find($t,$id,$d);}
 public function create(int $t,array $i,int $u,?array $photo=null):int{$d=$this->validate($i);if($this->m->nameExists($t,$d['name']))throw new RuntimeException('A guide with this name already exists.');$d['slug']=$this->slug($t,$this->slugify($d['name']));$d['profile_image_path']=null;$new=null;try{if($this->has($photo)){$d['profile_image_path']=$this->images->store($photo,'guide-profiles');$new=$d['profile_image_path'];}return $this->m->create($t,$d,$u);}catch(Throwable $e){if($new)$this->images->delete($new);throw $e;}}
 public function update(int $t,int $id,array $i,int $u,?array $photo=null):void{$old=$this->find($t,$id);if(!$old)throw new RuntimeException('Guide not found.');$d=$this->validate($i);if($this->m->nameExists($t,$d['name'],$id))throw new RuntimeException('A guide with this name already exists.');$d['slug']=$this->slug($t,$this->slugify($d['name']),$id);$d['profile_image_path']=$old['profile_image_path']??null;$new=null;try{if($this->has($photo)){$d['profile_image_path']=$this->images->store($photo,'guide-profiles');$new=$d['profile_image_path'];}elseif(!empty($i['remove_photo']))$d['profile_image_path']=null;$this->m->update($t,$id,$d,$u);}catch(Throwable $e){if($new)$this->images->delete($new);throw $e;}if(($old['profile_image_path']??null)!==$d['profile_image_path'])$this->images->delete($old['profile_image_path']??null);}
 public function delete(int $t,int $id,int $u):void{if(!$this->find($t,$id))throw new RuntimeException('Guide not found.');$this->m->softDelete($t,$id,$u);}public function restore(int $t,int $id,int $u):void{if(!$this->find($t,$id,true))throw new RuntimeException('Deleted guide not found.');$this->m->restore($t,$id,$u);}
 private function validate(array $i):array{$d=['business_id'=>($i['business_id']??'')===''?null:(int)$i['business_id'],'name'=>trim((string)($i['name']??'')),'bio'=>trim((string)($i['bio']??''))?:null,'phone'=>trim((string)($i['phone']??''))?:null,'email'=>trim((string)($i['email']??''))?:null,'city'=>trim((string)($i['city']??''))?:null,'district'=>trim((string)($i['district']??''))?:null,'state'=>trim((string)($i['state']??''))?:'Manipur','latitude'=>$this->coord($i['latitude']??null,-90,90,'Latitude'),'longitude'=>$this->coord($i['longitude']??null,-180,180,'Longitude'),'languages'=>trim((string)($i['languages']??''))?:null,'specializations'=>trim((string)($i['specializations']??''))?:null,'experience_years'=>($i['experience_years']??'')===''?null:max(0,(int)$i['experience_years']),'price_per_day'=>$this->money($i['price_per_day']??null),'verification_status'=>trim((string)($i['verification_status']??'Pending'))?:'Pending','status'=>trim((string)($i['status']??'Active'))?:'Active'];if(!$d['name'])throw new RuntimeException('Guide name is required.');if(($d['latitude']===null)!==($d['longitude']===null))throw new RuntimeException('Latitude and longitude must be provided together.');if(!in_array($d['verification_status'],['Pending','Verified','Rejected'],true)||!in_array($d['status'],['Active','Inactive','Suspended'],true))throw new RuntimeException('Invalid guide status.');return $d;}
 private function coord(mixed $v,float $min,float $max,string $n):?string{$v=trim((string)$v);if($v==='')return null;if(!is_numeric($v)||(float)$v<$min||(float)$v>$max)throw new RuntimeException($n.' must be between '.$min.' and '.$max.'.');return number_format((float)$v,7,'.','');}private function money(mixed $v):?string{$v=trim((string)$v);if($v==='')return null;if(!is_numeric($v)||(float)$v<0)throw new RuntimeException('Price per day must be a valid non-negative amount.');return number_format((float)$v,2,'.','');}private function has(?array $f):bool{return is_array($f)&&(int)($f['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_NO_FILE;}private function slug(int $t,string $b,?int $ignore=null):string{$b=$b?:'guide';$c=$b;$n=2;while($this->m->slugExists($t,$c,$ignore))$c=$b.'-'.$n++;return $c;}private function slugify(string $v):string{$v=strtolower(trim($v));$v=preg_replace('/[^a-z0-9]+/','-',$v)??'';return trim($v,'-');}
}
