<?php
declare(strict_types=1);
namespace App\Modules\Tourism\Services;
use App\Modules\Tourism\Models\TourismPackage;use RuntimeException;use Throwable;
final class TourismPackageService{
 private TourismPackage $m;private TourismImageUploadService $images;public function __construct(){$this->m=new TourismPackage();$this->images=new TourismImageUploadService();}
 public function all(int $t,bool $d=false):array{return $this->m->all($t,$d);}public function find(int $t,int $id,bool $d=false):?array{return $this->m->find($t,$id,$d);}public function destinations(int $t,int $id):array{return $this->m->destinations($t,$id);}public function providers(int $t):array{return $this->m->providers($t);}public function destinationsForSelect(int $t):array{return $this->m->destinationsForSelect($t);}
 public function create(int $t,array $i,int $u,?array $cover=null):int{$d=$this->validate($i);if($this->m->nameExists($t,$d['title']))throw new RuntimeException('A package with this title already exists.');$d['slug']=$this->slug($t,$this->slugify($d['title']));$d['cover_image_path']=null;$stored=null;try{if($this->has($cover)){$d['cover_image_path']=$this->images->store($cover,'package-covers');$stored=$d['cover_image_path'];}return $this->m->create($t,$d,$u);}catch(Throwable $e){if($stored)$this->images->delete($stored);throw $e;}}
 public function update(int $t,int $id,array $i,int $u,?array $cover=null):void{$old=$this->find($t,$id);if(!$old)throw new RuntimeException('Package not found.');$d=$this->validate($i);if($this->m->nameExists($t,$d['title'],$id))throw new RuntimeException('A package with this title already exists.');$d['slug']=$this->slug($t,$this->slugify($d['title']),$id);$d['cover_image_path']=$old['cover_image_path']??null;$new=null;try{if($this->has($cover)){$d['cover_image_path']=$this->images->store($cover,'package-covers');$new=$d['cover_image_path'];}elseif(!empty($i['remove_cover']))$d['cover_image_path']=null;$this->m->update($t,$id,$d,$u);}catch(Throwable $e){if($new)$this->images->delete($new);throw $e;}if(($old['cover_image_path']??null)!==$d['cover_image_path'])$this->images->delete($old['cover_image_path']??null);}
 public function delete(int $t,int $id,int $u):void{if(!$this->find($t,$id))throw new RuntimeException('Package not found.');$this->m->softDelete($t,$id,$u);}public function restore(int $t,int $id,int $u):void{if(!$this->find($t,$id,true))throw new RuntimeException('Deleted package not found.');$this->m->restore($t,$id,$u);}
 public function addDestination(int $t,int $id,array $i):void{$p=$this->find($t,$id);if(!$p)throw new RuntimeException('Package not found.');$dest=$this->destinationsForSelect($t);$valid=false;foreach($dest as $d)if((int)$d['id']===(int)($i['destination_id']??0)){$valid=true;break;}if(!$valid)throw new RuntimeException('Please select a valid destination.');$day=max(1,(int)($i['day_number']??1));$seq=max(1,(int)($i['sequence_no']??1));try{$this->m->addDestination($t,$id,(int)$i['destination_id'],$day,$seq,trim((string)($i['notes']??''))?:null);}catch(Throwable $e){throw new RuntimeException('This destination is already in the package.');}}
 public function removeDestination(int $t,int $id,int $relationId):void{$this->m->removeDestination($t,$id,$relationId);}
 private function validate(array $i):array{$d=['provider_id'=>($i['provider_id']??'')===''?null:(int)$i['provider_id'],'title'=>trim((string)($i['title']??'')),'description'=>trim((string)($i['description']??''))?:null,'duration_days'=>max(1,(int)($i['duration_days']??1)),'duration_nights'=>max(0,(int)($i['duration_nights']??0)),'pricing_type'=>trim((string)($i['pricing_type']??'PER_PERSON'))?:'PER_PERSON','base_price'=>$this->money($i['base_price']??0,'Base price'), 'discount_price'=>$this->money($i['discount_price']??null,'Discount price'),'max_travellers'=>($i['max_travellers']??'')===''?null:max(1,(int)$i['max_travellers']),'status'=>trim((string)($i['status']??'Draft'))?:'Draft'];if(!$d['title'])throw new RuntimeException('Package title is required.');if(!in_array($d['pricing_type'],['PER_PERSON','PER_GROUP'],true))throw new RuntimeException('Invalid pricing type.');if($d['discount_price']!==null&&(float)$d['discount_price']>(float)$d['base_price'])throw new RuntimeException('Discount price cannot exceed base price.');if(!in_array($d['status'],['Draft','Pending','Active','Inactive','Suspended'],true))throw new RuntimeException('Invalid package status.');return $d;}
 private function money(mixed $v,string $n):string{$v=trim((string)$v);if($v===''&&$n==='Discount price')return null;if(!is_numeric($v)||(float)$v<0)throw new RuntimeException($n.' must be a valid non-negative amount.');return number_format((float)$v,2,'.','');}private function has(?array $f):bool{return is_array($f)&&(int)($f['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_NO_FILE;}private function slug(int $t,string $b,?int $ignore=null):string{$b=$b?:'tour-package';$c=$b;$n=2;while($this->m->slugExists($t,$c,$ignore))$c=$b.'-'.$n++;return $c;}private function slugify(string $v):string{$v=strtolower(trim($v));$v=preg_replace('/[^a-z0-9]+/','-',$v)??'';return trim($v,'-');}
}
