<?php
declare(strict_types=1);
namespace App\Modules\Tourism\Services;
use App\Modules\Tourism\Models\TourismProvider;use RuntimeException;
final class TourismProviderService{
 private TourismProvider $m; public function __construct(){$this->m=new TourismProvider();}
 public function all(int $t,bool $d=false):array{return $this->m->all($t,$d);}public function find(int $t,int $id):?array{return $this->m->find($t,$id);}public function findDeleted(int $t,int $id):?array{return $this->m->findDeleted($t,$id);}
 public function create(int $t,array $i,int $u):int{$d=$this->validate($i);if($this->m->businessNameExists($t,$d['business_name']))throw new RuntimeException('A tourism provider with this business name already exists.');$d['business_slug']=$this->slug($t,$this->slugify($d['business_name']));return $this->m->create($t,$d,$u);}
 public function update(int $t,int $id,array $i,int $u):void{if(!$this->find($t,$id))throw new RuntimeException('Tourism provider not found.');$d=$this->validate($i);if($this->m->businessNameExists($t,$d['business_name'],$id))throw new RuntimeException('A tourism provider with this business name already exists.');$d['business_slug']=$this->slug($t,$this->slugify($d['business_name']),$id);$this->m->update($t,$id,$d,$u);}
 public function delete(int $t,int $id,int $u):void{if(!$this->find($t,$id))throw new RuntimeException('Tourism provider not found.');$this->m->softDelete($t,$id,$u);}public function restore(int $t,int $id,int $u):void{if(!$this->findDeleted($t,$id))throw new RuntimeException('Deleted tourism provider not found.');$this->m->restore($t,$id,$u);}
 public function locations():array{return ['state'=>['Manipur'],'districts'=>['Bishnupur','Chandel','Churachandpur','Imphal East','Imphal West','Jiribam','Kakching','Kamjong','Kangpokpi','Noney','Pherzawl','Senapati','Tamenglong','Tengnoupal','Thoubal','Ukhrul'],'cities'=>['Imphal','Bishnupur','Chandel','Churachandpur','Jiribam','Kakching','Kamjong','Kangpokpi','Noney','Pherzawl','Senapati','Tamenglong','Moreh','Thoubal','Ukhrul']];}
 private function validate(array $i):array{$d=[];foreach(['business_name','legal_name','phone','email','address','city','district','state','postal_code','description'] as $k)$d[$k]=$this->str($i[$k]??'');$d['provider_type']=$this->str($i['provider_type']??'OTHER')?:'OTHER';$d['latitude']=$this->coord($i['latitude']??null,-90,90,'Latitude');$d['longitude']=$this->coord($i['longitude']??null,-180,180,'Longitude');$d['state']=$d['state']?:'Manipur';$d['status']=$this->str($i['status']??'Active')?:'Active';if(!$d['business_name'])throw new RuntimeException('Business name is required.');if(($d['latitude']===null)!==($d['longitude']===null))throw new RuntimeException('Latitude and longitude must be provided together.');if(!in_array($d['provider_type'],['HOTEL','LODGE','HOMESTAY','RESORT','GUEST_HOUSE','TOUR_OPERATOR','TRAVEL_AGENCY','OTHER'],true))throw new RuntimeException('Invalid provider type.');if(!in_array($d['status'],['Active','Inactive','Suspended'],true))throw new RuntimeException('Invalid status.');return $d;}
 private function coord(mixed $v,float $min,float $max,string $n):?string{$v=trim((string)$v);if($v==='')return null;if(!is_numeric($v)||(float)$v<$min||(float)$v>$max)throw new RuntimeException($n.' must be between '.$min.' and '.$max.'.');return number_format((float)$v,7,'.','');}private function slug(int $t,string $b,?int $ignore=null):string{$b=$b?:'tourism-provider';$c=$b;$n=2;while($this->m->slugExists($t,$c,$ignore))$c=$b.'-'.$n++;return $c;}private function slugify(string $v):string{$v=strtolower(trim($v));$v=preg_replace('/[^a-z0-9]+/','-',$v)??'';return trim($v,'-');}private function str(mixed $v):?string{$v=trim((string)$v);return $v===''?null:$v;}
}
