<?php include __DIR__ . '/../Shared/member-desktop.css.php';
include __DIR__ . '/../Shared/member-desktop-header.php'; ?>
<?php require __DIR__.'/_style.php'; ?>
<div class="ma-tour"><header class="ma-tour-head"><a class="ma-tour-brand" href="<?=$basePath?>/member/tourism"><span class="ma-tour-mark">📍</span><span><strong>Destinations</strong><small>Places to explore</small></span></a><a class="ma-tour-back" href="<?=$basePath?>/member/tourism">← Explore</a></header>
<div class="ma-tour-list-head"><h1>Find your next place</h1><p>Discover destinations across Manipur.</p></div>
<form class="ma-tour-filter"><input name="q" value="<?=maTourEsc($search??'')?>" placeholder="Search destination or district…"><button>Search</button></form>
<form class="ma-tour-location-filter" method="get" action="<?=$basePath?>/member/tourism/destinations"><input type="hidden" name="q" value="<?=maTourEsc($_GET['q']??'')?>"><label>📍 Explore by district<select name="district" onchange="this.form.submit()"><option value="">All Manipur</option><?php foreach(($districts??[]) as $row): ?><option value="<?=maTourEsc($row['district'])?>" <?=($district??'')===$row['district']?'selected':''?>><?=maTourEsc($row['district'])?></option><?php endforeach; ?></select></label><button type="submit">Apply</button><?php if(!empty($district)): ?><a class="clear" href="<?=$basePath?>/member/tourism/destinations" style="text-decoration:none;padding:10px 14px;border-radius:11px">Clear</a><?php endif; ?></form>
<?php if(!$destinations):?><div class="ma-tour-empty">No destinations matched your search.</div><?php else:?><div class="ma-tour-grid"><?php foreach($destinations as $d):?><a class="ma-tour-card" href="<?=$basePath?>/member/tourism/destinations/<?=intval($d['id'])?>"><div class="ma-tour-media"><?php if(maTourImg($d['cover_image_path']??'')):?><img src="<?=maTourEsc($d['cover_image_path'])?>" alt="<?=maTourEsc($d['name'])?>"><?php else:?>🏞️<?php endif;?><span class="ma-tour-pill"><?=maTourEsc($d['district']??'Manipur')?></span></div><div class="ma-tour-card-body"><h3><?=maTourEsc($d['name'])?></h3><p><?=maTourEsc(mb_strimwidth((string)($d['description']??''),0,130,'…','UTF-8'))?></p><div class="ma-tour-meta"><?php if(!empty($d['best_time_to_visit'])):?><span>Best: <?=maTourEsc($d['best_time_to_visit'])?></span><?php endif;?><?php if(!empty($d['review_rating'])):?><span>★ <?=maTourEsc($d['review_rating'])?></span><?php endif;?></div></div></a><?php endforeach;?></div><?php endif;?>
</div>
<?php $aiScope = 'DESTINATIONS'; $aiContext = ''; include __DIR__ . '/../AI/ask.php'; ?>
