<?php include __DIR__ . '/../Shared/member-desktop.css.php';
include __DIR__ . '/../Shared/member-desktop-header.php'; ?>
<?php require __DIR__.'/_style.php';$d=$destination;$return=$basePath.'/member/tourism/destinations/'.intval($d['id']); ?>
<div class="ma-tour"><header class="ma-tour-head"><a class="ma-tour-brand" href="<?=$basePath?>/member/tourism"><span class="ma-tour-mark">📍</span><span><strong><?=maTourEsc($d['name'])?></strong><small><?=maTourEsc($d['district']??'Manipur')?></small></span></a><a class="ma-tour-back" href="<?=$basePath?>/member/tourism/destinations">← Destinations</a></header>
<div class="ma-tour-detail"><div class="ma-tour-cover"><?php if(maTourImg($d['cover_image_path']??'')):?><img src="<?=maTourEsc($d['cover_image_path'])?>" alt="<?=maTourEsc($d['name'])?>"><?php else:?>🏞️<?php endif;?></div><div class="ma-tour-detail-card"><h1><?=maTourEsc($d['name'])?></h1><div class="sub">📍 <?=maTourEsc(($d['city']??'').(($d['district']??'')?' · '.$d['district']:''))?> <?php if(!empty($d['review_rating'])):?> · ★ <?=maTourEsc($d['review_rating'])?> (<?=intval($d['review_count']??0)?>)<?php endif;?></div><div class="ma-tour-action"><a href="<?=$basePath?>/member/tourism/stays?destination_id=<?=intval($d['id'])?>">🏡 Find stays</a><a class="light" href="<?=$basePath?>/member/tourism/experiences?destination_id=<?=intval($d['id'])?>">✨ Things to do</a><a class="light" href="<?=$basePath?>/member/tourism/trips">🗺️ Plan this</a></div></div></div>
<div class="ma-tour-content"><div><section class="ma-tour-panel"><h2>About this place</h2><p><?=nl2br(maTourEsc((string)($d['description']??'Discover this destination in Manipur.')))?></p><div class="ma-tour-meta"><?php if(!empty($d['best_time_to_visit'])):?><span>Best time: <?=maTourEsc($d['best_time_to_visit'])?></span><?php endif;?><?php if(!empty($d['suggested_duration'])):?><span>Suggested: <?=maTourEsc($d['suggested_duration'])?></span><?php endif;?></div></section>
<?php if($stays):?><section class="ma-tour-panel" style="margin-top:14px"><h2>Stay nearby</h2><?php foreach(array_slice($stays,0,4) as $s):?><a class="ma-tour-trip-item" href="<?=$basePath?>/member/tourism/stays/<?=intval($s['id'])?>"><span class="ma-tour-trip-day">🏡</span><span><strong><?=maTourEsc($s['name'])?></strong><small><?=maTourEsc($s['stay_type']??'Stay')?> · <?=maTourEsc($s['city']??$s['district']??'')?></small></span><span>→</span></a><?php endforeach;?></section><?php endif;?>
<?php if($experiences):?><section class="ma-tour-panel" style="margin-top:14px"><h2>Experiences here</h2><?php foreach(array_slice($experiences,0,5) as $e):?><a class="ma-tour-trip-item" href="<?=$basePath?>/member/tourism/experiences/<?=intval($e['id'])?>"><span class="ma-tour-trip-day">✨</span><span><strong><?=maTourEsc($e['title'])?></strong><small><?=maTourEsc($e['experience_type']??'Experience')?><?php if(isset($e['price'])):?> · ₹<?=number_format((float)$e['price'],0)?><?php endif;?></small></span><span>→</span></a><?php endforeach;?></section><?php endif;?></div>
<aside><section class="ma-tour-panel"><h2>Visitor reviews</h2><?php if(!$reviews):?><p>No approved reviews yet. Be one of the first.</p><?php else:?><?php foreach(array_slice($reviews,0,6) as $r):?><div class="ma-tour-review"><div class="ma-tour-stars"><?=str_repeat('★',(int)$r['rating'])?><?=str_repeat('☆',5-(int)$r['rating'])?></div><strong><?=maTourEsc($r['title']??'Visitor review')?></strong><p><?=maTourEsc($r['review'])?></p><small><?=maTourEsc($r['reviewer_name']??'Visitor')?></small></div><?php endforeach;?><?php endif;?></section>
<?php include __DIR__.'/review-form.php';?></aside></div></div>
<?php include __DIR__ . '/../Shared/member-desktop-footer.php'; ?>
