<?php include __DIR__ . '/../Shared/member-desktop.css.php';
include __DIR__ . '/../Shared/member-desktop-header.php'; ?>
<?php require __DIR__.'/_style.php'; ?>
<div class="ma-tour"><header class="ma-tour-head"><a class="ma-tour-brand" href="<?=$basePath?>/member/tourism"><span class="ma-tour-mark">🎉</span><span><strong>Events & Festivals</strong><small>What's happening in Manipur</small></span></a><a class="ma-tour-back" href="<?=$basePath?>/member/tourism">← Explore</a></header>
<div class="ma-tour-list-head"><h1>Events worth planning around</h1><p>Festivals, community events and local happenings.</p></div>
<form class="ma-tour-filter"><input name="q" value="<?=maTourEsc($_GET['q']??'')?>" placeholder="Search events, venue or district…"><button>Search</button></form>
<form class="ma-tour-location-filter" method="get" action="<?=$basePath?>/member/tourism/events"><input type="hidden" name="q" value="<?=maTourEsc($_GET['q']??'')?>"><label>📍 Explore by district<select name="district" onchange="this.form.submit()"><option value="">All Manipur</option><?php foreach(($districts??[]) as $row): ?><option value="<?=maTourEsc($row['district'])?>" <?=($district??'')===$row['district']?'selected':''?>><?=maTourEsc($row['district'])?></option><?php endforeach; ?></select></label><button type="submit">Apply</button><?php if(!empty($district)): ?><a class="clear" href="<?=$basePath?>/member/tourism/events" style="text-decoration:none;padding:10px 14px;border-radius:11px">Clear</a><?php endif; ?></form>
<?php if(!$events):?><div class="ma-tour-empty">No events are available yet.</div><?php else:?><div class="ma-tour-grid"><?php foreach($events as $e):?><a class="ma-tour-card" href="<?=$basePath?>/member/tourism/events/<?=intval($e['id'])?>"><div class="ma-tour-media"><?php if(maTourImg($e['cover_image_path']??'')):?><img src="<?=maTourEsc($e['cover_image_path'])?>" alt="<?=maTourEsc($e['title'])?>"><?php else:?>🎉<?php endif;?><span class="ma-tour-pill"><?=maTourEsc($e['event_type']??'Event')?></span></div><div class="ma-tour-card-body"><h3><?=maTourEsc($e['title'])?></h3><p><?=maTourEsc(date('D, d M Y',strtotime((string)$e['start_at'])))?> · <?=maTourEsc($e['venue']??$e['district']??'Manipur')?></p><div class="ma-tour-meta"><?php if(!empty($e['ticket_info'])):?><span>Tickets / info available</span><?php endif;?></div></div></a><?php endforeach;?></div><?php endif;?>
</div>
<?php $aiScope = 'EVENTS'; $aiContext = ''; include __DIR__ . '/../AI/ask.php'; ?>
<?php include __DIR__ . '/../Shared/member-desktop-footer.php'; ?>
