<?php include __DIR__ . '/../Shared/member-desktop.css.php';
include __DIR__ . '/../Shared/member-desktop-header.php'; ?>
<?php require __DIR__.'/_style.php'; ?>
<div class="ma-tour"><header class="ma-tour-head"><a class="ma-tour-brand" href="<?=$basePath?>/member/tourism"><span class="ma-tour-mark">🧭</span><span><strong>Local Guides</strong><small>See Manipur with local knowledge</small></span></a><a class="ma-tour-back" href="<?=$basePath?>/member/tourism">← Explore</a></header>
<div class="ma-tour-list-head"><h1>Meet local guides</h1><p>People who can help you understand the places you visit.</p></div>
<form class="ma-tour-filter"><input name="q" value="<?=maTourEsc($_GET['q']??'')?>" placeholder="Search guide, language or speciality…"><button>Search</button></form>
<form class="ma-tour-location-filter" method="get" action="<?=$basePath?>/member/tourism/guides"><input type="hidden" name="q" value="<?=maTourEsc($_GET['q']??'')?>"><label>📍 Explore by district<select name="district" onchange="this.form.submit()"><option value="">All Manipur</option><?php foreach(($districts??[]) as $row): ?><option value="<?=maTourEsc($row['district'])?>" <?=($district??'')===$row['district']?'selected':''?>><?=maTourEsc($row['district'])?></option><?php endforeach; ?></select></label><button type="submit">Apply</button><?php if(!empty($district)): ?><a class="clear" href="<?=$basePath?>/member/tourism/guides" style="text-decoration:none;padding:10px 14px;border-radius:11px">Clear</a><?php endif; ?></form>
<?php if(!$guides):?><div class="ma-tour-empty">No guides found.</div><?php else:?><div class="ma-tour-grid"><?php foreach($guides as $g):$name=$g['full_name']??$g['name']??'Local Guide';?><a class="ma-tour-card" href="<?=$basePath?>/member/tourism/guides/<?=intval($g['id'])?>"><div class="ma-tour-media">🧭<span class="ma-tour-pill">Local guide</span></div><div class="ma-tour-card-body"><h3><?=maTourEsc($name)?></h3><p><?=maTourEsc(mb_strimwidth((string)($g['bio']??$g['profile']??''),0,120,'…','UTF-8'))?></p><div class="ma-tour-meta"><?php if(!empty($g['languages'])):?><span>🗣 <?=maTourEsc($g['languages'])?></span><?php endif;?><?php if(isset($g['price_per_day'])):?><span>₹<?=number_format((float)$g['price_per_day'],0)?> / day</span><?php endif;?></div></div></a><?php endforeach;?></div><?php endif;?>
</div>
<?php $aiScope = 'GUIDES'; $aiContext = "About this local guide: <?=maTourEsc($name??'this guide')?>"; include __DIR__ . '/../AI/ask.php'; ?>
