<?php include __DIR__ . '/../Shared/member-desktop.css.php';
include __DIR__ . '/../Shared/member-desktop-header.php'; ?>
<?php require __DIR__.'/_style.php'; ?>
<div class="ma-tour"><header class="ma-tour-head"><a class="ma-tour-brand" href="<?=$basePath?>/member/tourism"><span class="ma-tour-mark">🧳</span><span><strong>Tour Packages</strong><small>Ready-made journeys</small></span></a><a class="ma-tour-back" href="<?=$basePath?>/member/tourism">← Explore</a></header>
<div class="ma-tour-list-head"><h1>Journeys, already imagined</h1><p>Browse curated packages and their destination itineraries.</p></div>
<form class="ma-tour-filter" method="get"><input name="q" value="<?=maTourEsc($_GET['q']??'')?>" placeholder="Search packages…"><button>Search</button></form>
<form class="ma-tour-location-filter" method="get" action="<?=$basePath?>/member/tourism/packages"><input type="hidden" name="q" value="<?=maTourEsc($_GET['q']??'')?>"><label>📍 Explore by district<select name="district" onchange="this.form.submit()"><option value="">All Manipur</option><?php foreach(($districts??[]) as $row): ?><option value="<?=maTourEsc($row['district'])?>" <?=($district??'')===$row['district']?'selected':''?>><?=maTourEsc($row['district'])?></option><?php endforeach; ?></select></label><button type="submit">Apply</button><?php if(!empty($district)): ?><a class="clear" href="<?=$basePath?>/member/tourism/packages" style="text-decoration:none;padding:10px 14px;border-radius:11px">Clear</a><?php endif; ?></form>
<?php if(!$packages):?><div class="ma-tour-empty">No tour packages are available yet.</div><?php else:?><div class="ma-tour-grid"><?php foreach($packages as $p):$price=$p['discount_price']??null;$base=$p['base_price']??0;?><a class="ma-tour-card" href="<?=$basePath?>/member/tourism/packages/<?=intval($p['id'])?>"><div class="ma-tour-media"><?php if(maTourImg($p['cover_image_path']??'')):?><img src="<?=maTourEsc($p['cover_image_path'])?>" alt="<?=maTourEsc($p['title'])?>"><?php else:?>🗺️<?php endif;?><span class="ma-tour-pill"><?=intval($p['duration_days']??0)?> days</span></div><div class="ma-tour-card-body"><h3><?=maTourEsc($p['title'])?></h3><p><?=maTourEsc(mb_strimwidth((string)($p['description']??''),0,120,'…','UTF-8'))?></p><div class="ma-tour-meta"><span><?=intval($p['destination_count']??0)?> destinations</span><span>₹<?=number_format((float)($price!==null?$price:$base),0)?></span></div></div></a><?php endforeach;?></div><?php endif;?>
</div>
<?php $aiScope = 'PACKAGES'; $aiContext = ''; include __DIR__ . '/../AI/ask.php'; ?>
<?php include __DIR__ . '/../Shared/member-desktop-footer.php'; ?>
