<?php include __DIR__ . '/../Shared/member-desktop.css.php';
include __DIR__ . '/../Shared/member-desktop-header.php'; ?>
<?php require __DIR__.'/_style.php'; ?>
<div class="ma-tour"><header class="ma-tour-head"><a class="ma-tour-brand" href="<?=$basePath?>/member/tourism"><span class="ma-tour-mark">🏡</span><span><strong>Places to Stay</strong><small>Rest well in Manipur</small></span></a><a class="ma-tour-back" href="<?=$basePath?>/member/tourism">← Explore</a></header>
<div class="ma-tour-list-head"><h1>Stay your way</h1><p>Browse stays and room options from tourism providers.</p></div>
<form class="ma-tour-filter"><input name="q" value="<?=maTourEsc($search??'')?>" placeholder="Search stays, city or district…"><button>Search</button></form>
<form class="ma-tour-location-filter" method="get" action="<?=$basePath?>/member/tourism/stays"><input type="hidden" name="q" value="<?=maTourEsc($_GET['q']??'')?>"><label>📍 Explore by district<select name="district" onchange="this.form.submit()"><option value="">All Manipur</option><?php foreach(($districts??[]) as $row): ?><option value="<?=maTourEsc($row['district'])?>" <?=($district??'')===$row['district']?'selected':''?>><?=maTourEsc($row['district'])?></option><?php endforeach; ?></select></label><button type="submit">Apply</button><?php if(!empty($district)): ?><a class="clear" href="<?=$basePath?>/member/tourism/stays" style="text-decoration:none;padding:10px 14px;border-radius:11px">Clear</a><?php endif; ?></form>
<?php if(!$stays):?><div class="ma-tour-empty">No stays found.</div><?php else:?><div class="ma-tour-grid"><?php foreach($stays as $s):?><a class="ma-tour-card" href="<?=$basePath?>/member/tourism/stays/<?=intval($s['id'])?>"><div class="ma-tour-media"><?php if(maTourImg($s['cover_image_path']??'')):?><img src="<?=maTourEsc($s['cover_image_path'])?>" alt="<?=maTourEsc($s['name'])?>"><?php else:?>🛏️<?php endif;?><span class="ma-tour-pill"><?=maTourEsc($s['stay_type']??'Stay')?></span></div><div class="ma-tour-card-body"><h3><?=maTourEsc($s['name'])?></h3><p><?=maTourEsc(($s['city']??'').(($s['district']??'')?' · '.$s['district']:''))?></p><div class="ma-tour-meta"><?php $price=$s['starting_price_per_night']??$s['room_price']??null;if($price!==null):?><span>From ₹<?=number_format((float)$price,0)?> / night</span><?php endif;?><span><?=maTourEsc($s['provider_name']??'Tourism stay')?></span></div></div></a><?php endforeach;?></div><?php endif;?>
</div>
<?php $aiScope = 'STAYS'; $aiContext = ''; include __DIR__ . '/../AI/ask.php'; ?>
<?php include __DIR__ . '/../Shared/member-desktop-footer.php'; ?>
