SET NAMES utf8mb4;
START TRANSACTION;

CREATE TABLE IF NOT EXISTS `fresh_food_orders` (
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` char(36) NOT NULL,
  `tenant_id` bigint UNSIGNED NOT NULL,
  `fresh_food_id` bigint UNSIGNED NOT NULL,
  `member_id` bigint UNSIGNED DEFAULT NULL,
  `order_no` varchar(40) NOT NULL,
  `order_type` enum('DELIVERY','PICKUP') NOT NULL DEFAULT 'DELIVERY',
  `status` enum('PENDING','ACCEPTED','PACKING','READY','ASSIGNED','OUT_FOR_DELIVERY','DELIVERED','COMPLETED','CANCELLED','REJECTED') NOT NULL DEFAULT 'PENDING',
  `payment_status` enum('PENDING','PAID','FAILED','REFUNDED') NOT NULL DEFAULT 'PENDING',
  `payment_method` varchar(50) DEFAULT NULL,
  `customer_name` varchar(150) NOT NULL,
  `customer_phone` varchar(30) DEFAULT NULL,
  `customer_email` varchar(150) DEFAULT NULL,
  `delivery_address` text DEFAULT NULL,
  `delivery_city` varchar(100) DEFAULT NULL,
  `delivery_district` varchar(100) DEFAULT NULL,
  `delivery_state` varchar(100) DEFAULT NULL,
  `delivery_postal_code` varchar(20) DEFAULT NULL,
  `customer_latitude` decimal(10,7) DEFAULT NULL,
  `customer_longitude` decimal(10,7) DEFAULT NULL,
  `distance_km` decimal(10,3) DEFAULT NULL,
  `customer_note` text DEFAULT NULL,
  `gross_subtotal` decimal(12,2) NOT NULL DEFAULT 0.00,
  `item_discount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `delivery_fee` decimal(12,2) NOT NULL DEFAULT 0.00,
  `discount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `total` decimal(12,2) NOT NULL DEFAULT 0.00,
  `rejection_reason` text DEFAULT NULL,
  `cancellation_reason` text DEFAULT NULL,
  `accepted_at` timestamp NULL DEFAULT NULL,
  `packing_at` timestamp NULL DEFAULT NULL,
  `ready_at` timestamp NULL DEFAULT NULL,
  `assigned_at` timestamp NULL DEFAULT NULL,
  `out_for_delivery_at` timestamp NULL DEFAULT NULL,
  `delivered_at` timestamp NULL DEFAULT NULL,
  `completed_at` timestamp NULL DEFAULT NULL,
  `cancelled_at` timestamp NULL DEFAULT NULL,
  `rejected_at` timestamp NULL DEFAULT NULL,
  `delivery_assigned_to` bigint UNSIGNED DEFAULT NULL,
  `delivery_assigned_at` timestamp NULL DEFAULT NULL,
  `inventory_committed_at` timestamp NULL DEFAULT NULL,
  `inventory_released_at` timestamp NULL DEFAULT NULL,
  `created_by` bigint UNSIGNED DEFAULT NULL,
  `updated_by` bigint UNSIGNED DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `fresh_food_orders_uuid_unique` (`uuid`),
  UNIQUE KEY `fresh_food_orders_no_unique` (`tenant_id`,`order_no`),
  KEY `fresh_food_orders_tenant_index` (`tenant_id`),
  KEY `fresh_food_orders_business_index` (`fresh_food_id`),
  KEY `fresh_food_orders_member_index` (`member_id`),
  KEY `fresh_food_orders_status_index` (`tenant_id`,`status`),
  KEY `fresh_food_orders_created_index` (`created_at`),
  CONSTRAINT `fk_fresh_food_orders_profile` FOREIGN KEY (`fresh_food_id`) REFERENCES `fresh_food_profiles` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT `fk_fresh_food_orders_member` FOREIGN KEY (`member_id`) REFERENCES `members` (`id`) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT `fk_fresh_food_orders_delivery_user` FOREIGN KEY (`delivery_assigned_to`) REFERENCES `users` (`id`) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fresh_food_order_items` (
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` char(36) NOT NULL,
  `tenant_id` bigint UNSIGNED NOT NULL,
  `order_id` bigint UNSIGNED NOT NULL,
  `product_id` bigint UNSIGNED DEFAULT NULL,
  `product_name` varchar(200) NOT NULL,
  `unit` varchar(30) NOT NULL,
  `quantity` decimal(12,3) NOT NULL,
  `unit_price` decimal(12,2) NOT NULL DEFAULT 0.00,
  `discount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `line_total` decimal(12,2) NOT NULL DEFAULT 0.00,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `fresh_food_order_items_uuid_unique` (`uuid`),
  KEY `fresh_food_order_items_order_index` (`order_id`),
  KEY `fresh_food_order_items_product_index` (`product_id`),
  CONSTRAINT `fk_fresh_food_order_items_order` FOREIGN KEY (`order_id`) REFERENCES `fresh_food_orders` (`id`) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT `fk_fresh_food_order_items_product` FOREIGN KEY (`product_id`) REFERENCES `fresh_food_products` (`id`) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fresh_food_order_status_history` (
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` char(36) NOT NULL,
  `tenant_id` bigint UNSIGNED NOT NULL,
  `order_id` bigint UNSIGNED NOT NULL,
  `from_status` varchar(40) DEFAULT NULL,
  `to_status` varchar(40) NOT NULL,
  `note` text DEFAULT NULL,
  `changed_by` bigint UNSIGNED DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `fresh_food_order_status_history_uuid_unique` (`uuid`),
  KEY `fresh_food_order_status_history_order_index` (`order_id`),
  KEY `fresh_food_order_status_history_created_index` (`created_at`),
  CONSTRAINT `fk_fresh_food_order_status_history_order` FOREIGN KEY (`order_id`) REFERENCES `fresh_food_orders` (`id`) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT `fk_fresh_food_order_status_history_user` FOREIGN KEY (`changed_by`) REFERENCES `users` (`id`) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

COMMIT;
SET NAMES utf8mb4;
