<?php
declare(strict_types=1);
include __DIR__ . '/../Shared/member-desktop.css.php';
include __DIR__ . '/../Shared/member-desktop-header.php';

$base=rtrim((string)config('app.base_path'),'/');$r=$restaurant??null;$cart=$cart??['items'=>[]];$p=$preview??[];$coupon=$coupon??null;$csrf=(string)($csrf??'');
function rcEsc(mixed $v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function rcMoney(mixed $v):string{return '₹'.number_format((float)$v,2);}
?>
<style>
.rc-page{max-width:560px;margin:auto;padding:13px 13px 92px;color:#14251f}.rc-page *{box-sizing:border-box}.rc-head{display:flex;gap:9px;align-items:center}.rc-head a{font-size:27px;text-decoration:none;color:#173c32}.rc-head h1{margin:0;font-size:20px}.rc-head p{margin:2px 0;color:#74827d;font-size:10px}.rc-restaurant{display:flex;justify-content:space-between;gap:10px;background:#f1f6f3;border-radius:13px;padding:10px;margin:11px 0}.rc-restaurant b{font-size:13px}.rc-restaurant span{display:block;color:#6c7d75;font-size:9px;margin-top:2px}.rc-clear{border:0;background:#fff0ed;color:#a54b42;border-radius:8px;padding:7px 9px;font-size:9px;font-weight:900}.rc-line{display:grid;grid-template-columns:1fr auto;gap:9px;border-bottom:1px solid #edf2f0;padding:10px 0}.rc-name{font-size:12px;font-weight:900}.rc-detail{font-size:9px;color:#78867f;margin-top:3px}.rc-price{font-weight:900;font-size:12px;text-align:right}.rc-controls{display:flex;align-items:center;gap:6px;justify-content:flex-end;margin-top:7px}.rc-controls button{width:27px;height:27px;border:1px solid #dbe7e2;border-radius:8px;background:#fff;color:#087d64;font-weight:900}.rc-controls span{min-width:18px;text-align:center;font-size:10px;font-weight:900}.rc-min{padding:9px 10px;background:#fff8e9;border:1px solid #f0dfb9;border-radius:10px;font-size:9px;color:#6e6250;margin:9px 0}.rc-min.ok{background:#eaf7f2;border-color:#c6e8dc;color:#087d64}.rc-coupon{display:flex;gap:7px;margin:10px 0}.rc-coupon input{flex:1;border:1px solid #dce7e2;border-radius:9px;padding:9px;font-size:10px}.rc-coupon button{border:0;background:#173f34;color:#fff;border-radius:9px;padding:9px 12px;font-weight:900;font-size:9px}.rc-coupon-msg{font-size:9px;color:#087d64;margin:-5px 0 7px}.rc-summary{background:#f6faf8;border-radius:13px;padding:11px;margin-top:10px}.rc-row{display:flex;justify-content:space-between;padding:4px 0;font-size:10px;color:#61736b}.rc-row.total{font-size:15px;font-weight:950;color:#14251f;border-top:1px solid #dfeae5;margin-top:5px;padding-top:9px}.rc-row.discount{color:#087d64}.rc-checkout{display:block;text-align:center;text-decoration:none;background:#087d64;color:#fff;border-radius:13px;padding:12px;font-size:11px;font-weight:900;margin-top:10px}.rc-empty{text-align:center;background:#f3f8f5;border-radius:15px;padding:27px;color:#687a72;font-size:11px}.rc-empty b{display:block;color:#173d32;font-size:15px;margin-bottom:4px}.rc-nav{position:fixed;left:50%;bottom:6px;transform:translateX(-50%);width:min(540px,calc(100% - 14px));background:#fff;border:1px solid #e1ebe7;box-shadow:0 7px 22px rgba(0,0,0,.1);border-radius:18px;display:grid;grid-template-columns:repeat(4,1fr);padding:4px;z-index:30}.rc-nav a{text-decoration:none;color:#73827c;text-align:center;padding:5px 3px;font-size:9px;font-weight:700}.rc-nav a.active{color:#087d64}.rc-nav i{display:block;font-style:normal;font-size:17px}
</style>
<div class="rc-page"><header class="rc-head"><a href="<?=rcEsc($base)?>/member/restaurants">‹</a><div><h1>Your Cart</h1><p><?= $r?rcEsc($r['business_name']):'Restaurant cart'?></p></div></header>
<?php if(!$r||empty($cart['items'])): ?><div class="rc-empty"><b>Your cart is empty</b>Add delicious local food from a restaurant.<br><a class="rc-checkout" href="<?=rcEsc($base)?>/member/restaurants">Browse Restaurants</a></div><?php else: ?><div class="rc-restaurant"><div><b><?=rcEsc($r['business_name'])?></b><span><?=rcEsc($r['cuisine_type']??'Restaurant')?> · <?=!empty($r['is_open'])?'Open now':'Closed now'?></span></div><button class="rc-clear" id="clearCart">Clear Cart</button></div>
<?php foreach(($p['lines']??[]) as $line): ?><div class="rc-line"><div><div class="rc-name"><?=rcEsc($line['item_name'])?></div><div class="rc-detail"><?= $line['variant_name']?rcEsc($line['variant_name']).' · ':'' ?><?=rcMoney($line['unit_price'])?> each</div></div><div><div class="rc-price"><?=rcMoney($line['line_total'])?></div><div class="rc-controls"><button data-key="<?=rcEsc($line['key'])?>" data-qty="<?=max(0,(int)$line['quantity']-1)?>">−</button><span><?=rcEsc($line['quantity'])?></span><button data-key="<?=rcEsc($line['key'])?>" data-qty="<?=min(50,(int)$line['quantity']+1)?>">+</button></div></div></div><?php endforeach; ?>
<?php $min=(float)($p['minimum_order_amount']??0);$sub=(float)($p['subtotal']??0);$short=max(0,$min-$sub); ?><div class="rc-min <?=$short<=0?'ok':''?>"><?=$short>0?'Add '.rcMoney($short).' more to reach the minimum order.':'✓ Minimum order reached.'?></div>
<form class="rc-coupon" id="couponForm"><input type="hidden" name="_token" value="<?=rcEsc($csrf)?>"><input name="code" value="<?=rcEsc($cart['coupon_code']??'')?>" placeholder="Coupon code"><button>Apply</button></form><?php if($coupon): ?><div class="rc-coupon-msg">✓ <?=rcEsc($coupon['code'])?> applied · You save <?=rcMoney($coupon['discount'])?> <button type="button" id="removeCoupon" style="border:0;background:none;color:#a54b42;font-size:9px;font-weight:900">Remove</button></div><?php endif; ?>
<div class="rc-summary"><div class="rc-row"><span>Subtotal</span><b><?=rcMoney($p['subtotal']??0)?></b></div><?php if((float)($p['item_discount']??0)>0): ?><div class="rc-row discount"><span>Item discount</span><b>−<?=rcMoney($p['item_discount'])?></b></div><?php endif; ?><div class="rc-row"><span>Delivery fee</span><b><?=rcMoney($p['delivery_fee']??0)?></b></div><?php if((float)($p['coupon_discount']??0)>0): ?><div class="rc-row discount"><span>Coupon discount</span><b>−<?=rcMoney($p['coupon_discount'])?></b></div><?php endif; ?><div class="rc-row total"><span>Total</span><b><?=rcMoney($p['total']??0)?></b></div></div><a class="rc-checkout" href="<?=rcEsc($base)?>/member/restaurant/checkout">Proceed to Checkout →</a><?php endif; ?><?php include __DIR__ . '/../Shared/restaurant-cart-widget.php'; ?>
<?php include __DIR__ . '/../Shared/member-notification-widget.php'; ?>
</div>
<nav class="rc-nav"><a href="<?=rcEsc($base)?>/member"><i>⌂</i>Home</a><a class="active" href="<?=rcEsc($base)?>/member/restaurants"><i>🍛</i>Food</a><a href="<?=rcEsc($base)?>/member/bookings"><i>▣</i>Bookings</a><a href="<?=rcEsc($base)?>/member/profile"><i>♙</i>Profile</a></nav>
<script>
(()=>{const token=<?=json_encode($csrf)?>,base=<?=json_encode($base)?>;async function post(url,fd){const r=await fetch(url,{method:'POST',body:fd,headers:{Accept:'application/json'}});return r.json().catch(()=>({success:false,message:'Request failed.'}))}document.querySelectorAll('[data-key]').forEach(b=>b.addEventListener('click',async()=>{b.disabled=true;const fd=new FormData();fd.append('_token',token);fd.append('key',b.dataset.key);fd.append('quantity',b.dataset.qty);const j=await post(base+'/member/restaurant/cart/update',fd);if(j.success)location.reload();else{alert(j.message||'Unable to update cart.');b.disabled=false}}));document.getElementById('clearCart')?.addEventListener('click',async()=>{if(!confirm('Clear this cart?'))return;const fd=new FormData();fd.append('_token',token);const j=await post(base+'/member/restaurant/cart/clear',fd);if(j.success)location.reload();else alert(j.message||'Unable to clear cart.')});document.getElementById('couponForm')?.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.target);const j=await post(base+'/member/restaurant/coupon',fd);if(j.success)location.reload();else alert(j.message||'Coupon could not be applied.')});document.getElementById('removeCoupon')?.addEventListener('click',async()=>{const fd=new FormData();fd.append('_token',token);const j=await post(base+'/member/restaurant/coupon/remove',fd);if(j.success)location.reload();else alert(j.message||'Unable to remove coupon.')});})();
</script>
