<?php
declare(strict_types=1);
include __DIR__ . '/../Shared/member-desktop.css.php';
include __DIR__ . '/../Shared/member-desktop-header.php';

$base=rtrim((string)config('app.base_path'),'/');$r=$restaurant??[];$p=$preview??[];$profile=$profile??[];$coupon=$coupon??null;$old=$old??[];$csrf=(string)($csrf??'');
function coEsc(mixed $v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function coMoney(mixed $v):string{return '₹'.number_format((float)$v,2);}
?>
<style>
.co-page{max-width:560px;margin:auto;padding:13px 13px 92px;color:#14251f}.co-page *{box-sizing:border-box}.co-head{display:flex;gap:9px;align-items:center}.co-head a{font-size:27px;text-decoration:none;color:#173c32}.co-head h1{margin:0;font-size:20px}.co-head p{margin:2px 0;color:#74827d;font-size:10px}.co-card{background:#fff;border:1px solid #e1ebe6;border-radius:14px;padding:11px;margin:9px 0}.co-card h2{font-size:12px;margin:0 0 8px}.co-mode{display:grid;grid-template-columns:1fr 1fr;gap:6px}.co-mode label{border:1px solid #dce8e3;border-radius:10px;padding:10px;text-align:center;font-size:10px;font-weight:900}.co-mode input{display:none}.co-mode label.active{background:#eaf7f2;border-color:#9bd4c2;color:#087d64}.co-field{margin:8px 0}.co-field label{display:block;font-size:9px;font-weight:800;color:#596b63;margin-bottom:4px}.co-field input,.co-field textarea{width:100%;border:1px solid #dce7e2;border-radius:9px;padding:9px;font-size:10px;outline:0}.co-field textarea{min-height:65px;resize:vertical}.co-grid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.co-alert{background:#fff0ed;color:#93473f;border:1px solid #efccc5;border-radius:10px;padding:9px;font-size:10px;line-height:1.4}.co-info{background:#eaf7f2;color:#087d64;border-radius:10px;padding:9px;font-size:9px;line-height:1.4}.co-row{display:flex;justify-content:space-between;gap:8px;padding:4px 0;font-size:10px;color:#61736b}.co-row.discount{color:#087d64}.co-row.total{border-top:1px solid #dfeae5;margin-top:5px;padding-top:9px;font-size:15px;font-weight:950;color:#14251f}.co-place{width:100%;border:0;background:#087d64;color:#fff;border-radius:13px;padding:13px;font-size:11px;font-weight:900;margin-top:9px}.co-place:disabled{background:#aab9b3}.co-note{font-size:8px;color:#7a8983;line-height:1.4;margin-top:7px}.co-nav{position:fixed;left:50%;bottom:6px;transform:translateX(-50%);width:min(540px,calc(100% - 14px));background:#fff;border:1px solid #e1ebe7;box-shadow:0 7px 22px rgba(0,0,0,.1);border-radius:18px;display:grid;grid-template-columns:repeat(4,1fr);padding:4px;z-index:30}.co-nav a{text-decoration:none;color:#73827c;text-align:center;padding:5px 3px;font-size:9px;font-weight:700}.co-nav a.active{color:#087d64}.co-nav i{display:block;font-style:normal;font-size:17px}
</style>
<div class="co-page"><header class="co-head"><a href="<?=coEsc($base)?>/member/restaurant/cart">‹</a><div><h1>Checkout</h1><p><?=coEsc($r['business_name']??'Restaurant')?></p></div></header>
<?php if(!empty($error)): ?><div class="co-alert"><?=coEsc($error)?></div><?php endif; ?>
<form method="post" action="<?=coEsc($base)?>/member/restaurant/orders" id="checkoutForm"><input type="hidden" name="_token" value="<?=coEsc($csrf)?>"><section class="co-card"><h2>How would you like your order?</h2><div class="co-mode"><label id="deliveryLabel" class="active"><input type="radio" name="order_type" value="DELIVERY" <?=strtoupper((string)($old['order_type']??'DELIVERY'))==='DELIVERY'?'checked':''?>>🚚 Delivery</label><label id="pickupLabel"><input type="radio" name="order_type" value="PICKUP" <?=strtoupper((string)($old['order_type']??''))==='PICKUP'?'checked':''?>>🛍 Pickup</label></div></section>
<section class="co-card" id="addressCard"><h2>Deliver to</h2><div class="co-info">Your saved member address is pre-filled. You can change it for this order.</div><div class="co-field"><label>Address *</label><input required name="delivery_address" value="<?=coEsc($old['delivery_address']??$profile['address']??'')?>" placeholder="House, street, locality"></div><div class="co-grid"><div class="co-field"><label>City</label><input name="delivery_city" value="<?=coEsc($old['delivery_city']??$profile['city']??'')?>"></div><div class="co-field"><label>District</label><input name="delivery_district" value="<?=coEsc($old['delivery_district']??'')?>"></div><div class="co-field"><label>State</label><input name="delivery_state" value="<?=coEsc($old['delivery_state']??$profile['state']??'Manipur')?>"></div><div class="co-field"><label>Postal Code</label><input name="delivery_postal_code" value="<?=coEsc($old['delivery_postal_code']??$profile['postal_code']??'')?>"></div></div></section>
<section class="co-card" id="pickupCard" hidden><h2>Customer Pickup</h2><div class="co-info">You will collect this order from <?=coEsc($r['business_name']??'the restaurant')?>. No delivery address is required.</div><div class="co-note"><?=coEsc($r['address']??'')?><?php if(!empty($r['city'])): ?> · <?=coEsc($r['city'])?><?php endif;?></div></section>
<section class="co-card"><h2>Order note</h2><div class="co-field"><textarea name="customer_note" placeholder="Optional instructions for the restaurant..."><?=coEsc($old['customer_note']??'')?></textarea></div></section>
<section class="co-card"><h2>Order Summary</h2><div class="co-row"><span>Subtotal</span><b><?=coMoney($p['subtotal']??0)?></b></div><?php if((float)($p['item_discount']??0)>0): ?><div class="co-row discount"><span>Item discount</span><b>−<?=coMoney($p['item_discount'])?></b></div><?php endif; ?><div class="co-row" id="deliveryRow"><span>Delivery fee</span><b><?=coMoney($p['delivery_fee']??0)?></b></div><?php if($coupon): ?><div class="co-row discount"><span>Coupon (<?=coEsc($coupon['code'])?>)</span><b>−<?=coMoney($coupon['discount'])?></b></div><input type="hidden" name="coupon_code" value="<?=coEsc($coupon['code'])?>"><?php endif; ?><div class="co-row total"><span>Total</span><b id="totalValue"><?=coMoney($p['total']??0)?></b></div></section><button class="co-place" type="submit" id="placeOrder">Place Order · <?=coMoney($p['total']??0)?></button><div class="co-note">Payment gateway integration will be added later. This first MemberApp ordering flow records the order securely with the restaurant.</div></form><?php include __DIR__ . '/../Shared/restaurant-cart-widget.php'; ?>
<?php include __DIR__ . '/../Shared/member-notification-widget.php'; ?>
</div>
<nav class="co-nav"><a href="<?=coEsc($base)?>/member"><i>⌂</i>Home</a><a class="active" href="<?=coEsc($base)?>/member/restaurants"><i>🍛</i>Food</a><a href="<?=coEsc($base)?>/member/bookings"><i>▣</i>Bookings</a><a href="<?=coEsc($base)?>/member/profile"><i>♙</i>Profile</a></nav>
<script>(()=>{const d=document.querySelectorAll('input[name="order_type"]'),dl=document.getElementById('deliveryLabel'),pl=document.getElementById('pickupLabel'),a=document.getElementById('addressCard'),pc=document.getElementById('pickupCard'),ar=document.querySelector('[name="delivery_address"]');function sync(){const delivery=document.querySelector('input[name="order_type"]:checked')?.value==='DELIVERY';dl.classList.toggle('active',delivery);pl.classList.toggle('active',!delivery);a.hidden=!delivery;pc.hidden=delivery;ar.required=delivery}d.forEach(x=>x.addEventListener('change',sync));sync()})();</script>
<?php include __DIR__ . '/../Shared/member-desktop-footer.php'; ?>
