<?php
declare(strict_types=1);
include __DIR__ . '/../Shared/member-desktop.css.php';
include __DIR__ . '/../Shared/member-desktop-header.php';

$base=rtrim((string)config('app.base_path'),'/');$r=$restaurant??[];$i=$item??[];$csrf=(string)($csrf??'');
function riEsc(mixed $v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function riMoney(mixed $v):string{return '₹'.number_format((float)$v,0);}
function riImage(?string $p,string $b):?string{return $p?$b.'/'.ltrim($p,'/'):null;}
function riRating(mixed $id):array{$n=abs((int)sprintf('%u',crc32('item:'.(string)$id)));return [round(4.5+(($n%5)/10),1),70+($n%351)];}
$img=riImage($i['image_path']??null,$base);[$riRating,$riReviews]=riRating($i['id']??0);$old=(float)($i['price']??0);$price=(float)($i['display_price']??$old);$discount=max(0,$old-$price);
?>
<style>
.ri-page{max-width:560px;margin:auto;padding-bottom:90px;color:#14251f}.ri-page *{box-sizing:border-box}.ri-hero{height:235px;background:#edf4f1;position:relative}.ri-hero img{width:100%;height:100%;object-fit:cover}.ri-back{position:absolute;top:10px;left:11px;width:34px;height:34px;border-radius:50%;background:rgba(255,255,255,.92);display:grid;place-items:center;text-decoration:none;color:#173c32;font-size:23px}.ri-body{padding:13px}.ri-title{font-size:21px;font-weight:950}.ri-sub{font-size:10px;color:#75837d;margin-top:3px}.ri-price{font-size:22px;font-weight:950;margin-top:8px}.ri-old{text-decoration:line-through;color:#9ba59f;font-size:11px;margin-left:6px}.ri-off{background:#fff0ed;color:#c44b3f;border-radius:6px;padding:4px 6px;font-size:8px;font-weight:900;margin-left:5px}.ri-desc{font-size:11px;color:#667770;line-height:1.5;margin:8px 0 13px}.ri-group{margin:12px 0}.ri-group h2{font-size:13px;margin:0}.ri-help{font-size:9px;color:#87938e;margin:3px 0 7px}.ri-option{display:flex;align-items:center;justify-content:space-between;gap:8px;border:1px solid #dfe9e5;border-radius:10px;padding:9px;margin:6px 0;font-size:10px}.ri-option input{accent-color:#087d64}.ri-option.disabled{opacity:.5;background:#f5f7f6}.ri-option-left{display:flex;align-items:center;gap:7px}.ri-qty{display:flex;align-items:center;gap:10px;justify-content:center;margin:16px 0}.ri-qty button{width:34px;height:34px;border:1px solid #d7e4de;border-radius:10px;background:#fff;font-size:17px;color:#087d64}.ri-qty input{width:40px;border:0;text-align:center;font-weight:900;font-size:14px}.ri-submit{position:fixed;left:50%;bottom:7px;transform:translateX(-50%);width:min(540px,calc(100% - 14px));z-index:30;border:0;background:#087d64;color:#fff;border-radius:14px;padding:13px;font-weight:900;font-size:12px;box-shadow:0 8px 20px rgba(8,125,100,.25)}.ri-submit:disabled{background:#a9b9b3;box-shadow:none}.ri-alert{background:#fff0ed;color:#9b463d;border:1px solid #f0cfc9;border-radius:10px;padding:9px;font-size:10px;margin:9px 0}
</style>
<div class="ri-page"><div class="ri-hero"><?php if($img): ?><img src="<?=riEsc($img)?>" alt="<?=riEsc($i['name'])?>"><?php endif; ?><a class="ri-back" href="<?=riEsc($base)?>/member/restaurants/<?=riEsc($r['id'])?>">‹</a></div><form id="itemForm" method="post" action="<?=riEsc($base)?>/member/restaurant/cart/add"><input type="hidden" name="_token" value="<?=riEsc($csrf)?>"><input type="hidden" name="restaurant_id" value="<?=riEsc($r['id'])?>"><input type="hidden" name="item_id" value="<?=riEsc($i['id'])?>"><div class="ri-body"><div class="ri-title"><?=riEsc($i['name'])?></div><div class="ri-sub"><?=riEsc($i['category_name']??'')?> · <?=!empty($i['is_veg'])?'Vegetarian':'Non-vegetarian'?></div><div style="margin-top:5px;font-size:10px;color:#697a72"><strong style="color:#eca916">★ <?=number_format($riRating,1)?></strong> · <?=number_format($riReviews)?> reviews</div><div class="ri-price" id="price">₹<?=number_format($price,0)?><?php if($discount>0): ?><span class="ri-old">₹<?=number_format($old,0)?></span><span class="ri-off"><?=round($discount/$old*100)?>% OFF</span><?php endif;?></div><?php if(!empty($i['description'])):?><div class="ri-desc"><?=nl2br(riEsc($i['description']))?></div><?php endif;?>
<?php if(!empty($i['variants'])): ?><section class="ri-group"><h2>Choose Variant <?=array_reduce($i['variants'],static fn($c,$v)=>$c+(empty($v['is_available'])?0:1),0)>0?'*':''?></h2><div class="ri-help">Select the size or serving you want.</div><?php foreach($i['variants'] as $idx=>$v): ?><label class="ri-option <?=empty($v['is_available'])?'disabled':''?>"><span class="ri-option-left"><input type="radio" name="variant_id" value="<?=riEsc($v['id'])?>" data-price="<?=riEsc($v['price'])?>" <?=!empty($v['is_available'])&&$idx===0?'checked':''?> <?=empty($v['is_available'])?'disabled':''?>><?=riEsc($v['name'])?></span><b><?=riMoney($v['price'])?></b></label><?php endforeach;?></section><?php endif;?>
<?php foreach(($i['modifier_groups']??[]) as $g): $single=($g['selection_type']??'SINGLE')==='SINGLE'; $required=!empty($g['is_required'])||((int)($g['min_selections']??0)>0); ?><section class="ri-group"><h2><?=riEsc($g['name'])?> <?=$required?'*':''?></h2><div class="ri-help"><?=riEsc($g['description']??'')?><?php if(isset($g['min_selections'])||isset($g['max_selections'])): ?> · Choose <?=($g['min_selections']??0)>0?'at least '.(int)$g['min_selections'].' ':''?><?=($g['max_selections']??null)!==null?'up to '.(int)$g['max_selections']:''?><?php endif;?></div><?php foreach($g['options'] as $o): ?><label class="ri-option <?=empty($o['is_available'])?'disabled':''?>"><span class="ri-option-left"><input type="checkbox" name="modifier_option_ids[]" value="<?=riEsc($o['id'])?>" data-group="<?=riEsc($g['id'])?>" data-single="<?= $single?'1':'0' ?>" <?=empty($o['is_available'])?'disabled':''?>><?=riEsc($o['name'])?></span><b><?=((float)$o['price_adjustment']>0?'+':'').riMoney($o['price_adjustment'])?></b></label><?php endforeach;?></section><?php endforeach;?>
<div class="ri-qty"><button type="button" id="minus">−</button><input id="qty" name="quantity" value="1" inputmode="numeric" readonly><button type="button" id="plus">+</button></div><div class="ri-alert" id="formError" hidden></div></div></form></div><button class="ri-submit" id="addBtn" type="submit" form="itemForm" <?=empty($i['is_available'])?'disabled':''?>>Add to Cart · ₹<?=number_format($price,0)?></button>
<script>
(()=>{const f=document.getElementById('itemForm'),btn=document.getElementById('addBtn'),err=document.getElementById('formError'),qty=document.getElementById('qty'),priceEl=document.getElementById('price');let base=<?=json_encode($price)?>;const variants=[...document.querySelectorAll('input[name="variant_id"]')];function selectedBase(){const v=variants.find(x=>x.checked);return v?Number(v.dataset.price||base):base}function update(){let total=selectedBase();document.querySelectorAll('input[name="modifier_option_ids[]"]:checked').forEach(x=>{const label=x.closest('.ri-option');const text=label?.querySelector('b')?.textContent||'0';total+=Number(text.replace(/[^0-9.-]/g,''))||0;});const q=Number(qty.value||1);btn.textContent='Add to Cart · ₹'+Math.round(total*q).toLocaleString('en-IN')}variants.forEach(x=>x.addEventListener('change',update));document.querySelectorAll('input[name="modifier_option_ids[]"]').forEach(x=>x.addEventListener('change',()=>{if(x.checked&&x.dataset.single==='1'){document.querySelectorAll('input[name="modifier_option_ids[]"][data-group="'+CSS.escape(x.dataset.group||'')+'"]').forEach(y=>{if(y!==x)y.checked=false})}update()}));document.getElementById('minus').onclick=()=>{qty.value=Math.max(1,Number(qty.value)-1);update()};document.getElementById('plus').onclick=()=>{qty.value=Math.min(50,Number(qty.value)+1);update()};f.addEventListener('submit',async e=>{e.preventDefault();err.hidden=true;const r=await fetch(f.action,{method:'POST',body:new FormData(f),headers:{Accept:'application/json'}});const j=await r.json().catch(()=>({success:false,message:'Unable to add this item.'}));if(j.success){location.href=j.redirect}else if(j.code==='DIFFERENT_RESTAURANT'&&confirm(j.message+' Clear the current cart and continue?')){const fd=new FormData();fd.append('_token',f.querySelector('[name="_token"]').value);await fetch(<?=json_encode($base.'/member/restaurant/cart/clear')?>,{method:'POST',body:fd});f.dispatchEvent(new Event('submit'))}else{err.textContent=j.message||'Unable to add this item.';err.hidden=false}});update()})();
</script>
