<?php declare(strict_types=1); $base=config('app.base_path'); $r=$record??$old??[]; $locations=$locations??[]; ?>
<div class="card"><h2>Business Details</h2><div class="form-grid">
<div class="form-group"><label>Business Name *</label><input name="business_name" required value="<?= htmlspecialchars((string)($r['business_name']??''),ENT_QUOTES,'UTF-8') ?>"></div>
<div class="form-group"><label>Phone</label><input name="phone" value="<?= htmlspecialchars((string)($r['phone']??''),ENT_QUOTES,'UTF-8') ?>"></div>
<div class="form-group"><label>Email</label><input type="email" name="email" value="<?= htmlspecialchars((string)($r['email']??''),ENT_QUOTES,'UTF-8') ?>"></div>
<div class="form-group full-width"><label>Address</label><input name="address" value="<?= htmlspecialchars((string)($r['address']??''),ENT_QUOTES,'UTF-8') ?>"></div>
<div class="form-group"><label>State</label><select name="state"><?php foreach(($locations['state']??['Manipur']) as $v): ?><option <?= (($r['state']??'Manipur')===$v)?'selected':'' ?>><?= htmlspecialchars($v,ENT_QUOTES,'UTF-8') ?></option><?php endforeach; ?></select></div>
<div class="form-group"><label>District</label><select name="district"><option value="">Select district</option><?php foreach(($locations['districts']??[]) as $v): ?><option <?= (($r['district']??'')===$v)?'selected':'' ?>><?= htmlspecialchars($v,ENT_QUOTES,'UTF-8') ?></option><?php endforeach; ?></select></div>
<div class="form-group"><label>City / Town</label><select name="city"><option value="">Select city</option><?php foreach(($locations['cities']??[]) as $v): ?><option <?= (($r['city']??'')===$v)?'selected':'' ?>><?= htmlspecialchars($v,ENT_QUOTES,'UTF-8') ?></option><?php endforeach; ?></select></div>
<div class="form-group"><label>Postal Code</label><input name="postal_code" value="<?= htmlspecialchars((string)($r['postal_code']??''),ENT_QUOTES,'UTF-8') ?>"></div>
<div class="form-group full-width"><label>Description</label><textarea name="description" rows="3"><?= htmlspecialchars((string)($r['description']??''),ENT_QUOTES,'UTF-8') ?></textarea></div>
</div></div>
<div class="card"><h2>Location</h2><p class="help">Coordinates power nearby discovery and Haversine distance calculations in the Member PWA.</p><div class="form-grid"><div class="form-group"><label>Latitude</label><input id="ff-lat" type="number" step="0.0000001" min="-90" max="90" name="latitude" value="<?= htmlspecialchars((string)($r['latitude']??''),ENT_QUOTES,'UTF-8') ?>"></div><div class="form-group"><label>Longitude</label><input id="ff-lng" type="number" step="0.0000001" min="-180" max="180" name="longitude" value="<?= htmlspecialchars((string)($r['longitude']??''),ENT_QUOTES,'UTF-8') ?>"></div><div class="form-group full-width"><button type="button" class="btn btn-secondary" id="ff-location">Use Current Location</button> <span id="ff-location-msg" class="help"></span></div></div></div>
<div class="card"><h2>Delivery & Pre-order</h2><div class="form-grid">
<div class="form-group"><label>Minimum Delivery Fee (₹)</label><input type="number" step="0.01" min="0" name="minimum_delivery_fee" value="<?= htmlspecialchars((string)($r['minimum_delivery_fee']??'20.00'),ENT_QUOTES,'UTF-8') ?>"></div>
<div class="form-group"><label>Included Distance (km)</label><input type="number" step="0.01" min="0.01" name="included_delivery_distance_km" value="<?= htmlspecialchars((string)($r['included_delivery_distance_km']??'3.00'),ENT_QUOTES,'UTF-8') ?>"></div>
<div class="form-group"><label>Additional Fee / km (₹)</label><input type="number" step="0.01" min="0" name="additional_delivery_fee_per_km" value="<?= htmlspecialchars((string)($r['additional_delivery_fee_per_km']??'10.00'),ENT_QUOTES,'UTF-8') ?>"></div>
<div class="form-group"><label>Maximum Delivery Distance (km)</label><input type="number" step="0.01" min="0" name="max_delivery_distance_km" value="<?= htmlspecialchars((string)($r['max_delivery_distance_km']??''),ENT_QUOTES,'UTF-8') ?>"><small>Leave blank for no configured maximum.</small></div>
<div class="form-group"><label>Pre-order Delivery Fee (₹)</label><input type="number" step="0.01" min="0" name="preorder_delivery_fee" value="<?= htmlspecialchars((string)($r['preorder_delivery_fee']??'20.00'),ENT_QUOTES,'UTF-8') ?>"></div>
<div class="form-group"><label>Minimum Advance Hours</label><input type="number" min="1" name="preorder_min_advance_hours" value="<?= (int)($r['preorder_min_advance_hours']??24) ?>"></div>
<div class="form-group"><label>Packing Time Minimum (minutes)</label><input type="number" min="1" name="estimated_packing_minutes_min" value="<?= (int)($r['estimated_packing_minutes_min']??10) ?>"></div>
<div class="form-group"><label>Packing Time Maximum (minutes)</label><input type="number" min="1" name="estimated_packing_minutes_max" value="<?= (int)($r['estimated_packing_minutes_max']??20) ?>"></div>
<div class="form-group full-width"><label><input type="checkbox" name="delivery_available" value="1" <?= !empty($r['delivery_available'])?'checked':'' ?>> Delivery available</label><br><label><input type="checkbox" name="pickup_available" value="1" <?= !empty($r['pickup_available'])?'checked':'' ?>> Pickup available</label><br><label><input type="checkbox" name="preorder_enabled" value="1" <?= !empty($r['preorder_enabled'])?'checked':'' ?>> Enable pre-order pricing</label><br><label><input type="checkbox" name="accepting_orders" value="1" <?= !empty($r['accepting_orders'])?'checked':'' ?>> Accepting orders</label></div>
<div class="form-group"><label>Status</label><select name="status"><?php foreach(['Active','Inactive','Suspended'] as $s): ?><option <?= (($r['status']??'Active')===$s)?'selected':'' ?>><?= $s ?></option><?php endforeach; ?></select></div>
</div></div>
<script>document.getElementById('ff-location')?.addEventListener('click',function(){const m=document.getElementById('ff-location-msg');if(!navigator.geolocation){m.textContent='Geolocation is not supported by this browser.';return;}m.textContent='Getting location…';navigator.geolocation.getCurrentPosition(p=>{document.getElementById('ff-lat').value=p.coords.latitude.toFixed(7);document.getElementById('ff-lng').value=p.coords.longitude.toFixed(7);m.textContent='Location captured.';},e=>{m.textContent=e.message||'Unable to get location.'},{enableHighAccuracy:true,timeout:10000});});</script>
<style>.help{color:#64748b;font-size:13px}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.full-width{grid-column:1/-1}.form-group label{display:block;font-weight:600;margin-bottom:7px}.form-group input,.form-group select,.form-group textarea{width:100%;box-sizing:border-box}.form-group small{display:block;color:#64748b;margin-top:5px}@media(max-width:700px){.form-grid{grid-template-columns:1fr}.full-width{grid-column:auto}}</style>
