<?php declare(strict_types=1); $base=config('app.base_path'); $r=$record??$old??[]; ?>
<div class="card"><div class="form-grid">
<div class="form-group"><label>Fresh Food Business *</label><select name="fresh_food_id" required><option value="">Select business</option><?php foreach(($businesses??[]) as $b): ?><option value="<?= (int)$b['id'] ?>" <?= (int)($r['fresh_food_id']??0)===(int)$b['id']?'selected':'' ?>><?= htmlspecialchars((string)$b['business_name'],ENT_QUOTES,'UTF-8') ?></option><?php endforeach; ?></select></div>
<div class="form-group"><label>Coupon Code *</label><input name="code" required maxlength="80" value="<?= htmlspecialchars((string)($r['code']??''),ENT_QUOTES,'UTF-8') ?>" placeholder="FRESH10"></div>
<div class="form-group"><label>Coupon Name *</label><input name="name" required maxlength="150" value="<?= htmlspecialchars((string)($r['name']??''),ENT_QUOTES,'UTF-8') ?>"></div>
<div class="form-group"><label>Discount Type *</label><select name="discount_type"><option value="PERCENT" <?= (($r['discount_type']??'PERCENT')==='PERCENT')?'selected':'' ?>>Percentage (%)</option><option value="FLAT" <?= (($r['discount_type']??'')==='FLAT')?'selected':'' ?>>Flat (₹)</option></select></div>
<div class="form-group"><label>Discount Value *</label><input type="number" step="0.01" min="0.01" name="discount_value" required value="<?= htmlspecialchars((string)($r['discount_value']??'10'),ENT_QUOTES,'UTF-8') ?>"></div>
<div class="form-group"><label>Minimum Order Amount</label><input type="number" step="0.01" min="0" name="minimum_order_amount" value="<?= htmlspecialchars((string)($r['minimum_order_amount']??'0'),ENT_QUOTES,'UTF-8') ?>"></div>
<div class="form-group"><label>Maximum Discount</label><input type="number" step="0.01" min="0" name="maximum_discount" value="<?= htmlspecialchars((string)($r['maximum_discount']??''),ENT_QUOTES,'UTF-8') ?>"><small>Useful for percentage coupons.</small></div>
<div class="form-group"><label>Usage Limit</label><input type="number" min="1" name="usage_limit" value="<?= htmlspecialchars((string)($r['usage_limit']??''),ENT_QUOTES,'UTF-8') ?>"><small>Leave blank for unlimited.</small></div>
<div class="form-group"><label>Starts At</label><input type="datetime-local" name="starts_at" value="<?= htmlspecialchars(isset($r['starts_at'])&&$r['starts_at']?date('Y-m-d\TH:i',strtotime((string)$r['starts_at'])):'',ENT_QUOTES,'UTF-8') ?>"></div>
<div class="form-group"><label>Ends At</label><input type="datetime-local" name="ends_at" value="<?= htmlspecialchars(isset($r['ends_at'])&&$r['ends_at']?date('Y-m-d\TH:i',strtotime((string)$r['ends_at'])):'',ENT_QUOTES,'UTF-8') ?>"></div>
<div class="form-group"><label>Status</label><select name="status"><option value="Active" <?= (($r['status']??'Active')==='Active')?'selected':'' ?>>Active</option><option value="Inactive" <?= (($r['status']??'')==='Inactive')?'selected':'' ?>>Inactive</option></select></div>
<div class="form-group full-width"><label>Description</label><textarea name="description" rows="3"><?= htmlspecialchars((string)($r['description']??''),ENT_QUOTES,'UTF-8') ?></textarea></div>
</div></div><style>.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.full-width{grid-column:1/-1}.form-group label{display:block;font-weight:600;margin-bottom:7px}.form-group input,.form-group select,.form-group textarea{width:100%;box-sizing:border-box}.form-group small{display:block;margin-top:5px;opacity:.7}@media(max-width:700px){.form-grid{grid-template-columns:1fr}.full-width{grid-column:auto}}</style>
