<?php
declare(strict_types=1);
namespace App\Modules\FreshFood\Services;
use App\Modules\FreshFood\Models\FreshFood;
use RuntimeException;
final class FreshFoodService {
 private FreshFood $m; public function __construct(){ $this->m=new FreshFood(); }
 public function all(int $t,bool $d=false):array{return $this->m->all($t,$d);} public function find(int $t,int $id):?array{return $this->m->find($t,$id);} public function findDeleted(int $t,int $id):?array{return $this->m->findDeleted($t,$id);} public function trash(int $t):array{return $this->m->all($t,true);} public function dashboard(int $t):array{return $this->m->dashboard($t);} public function hours(int $t,int $id):array{return $this->m->hours($t,$id);}
 public function create(int $t,array $i,int $u):int{$d=$this->validate($i);if($this->m->nameExists($t,$d['business_name']))throw new RuntimeException('A Fresh Food business with this name already exists.');$d['business_slug']=$this->slug($t,$this->slugify($d['business_name']));return $this->m->create($t,$d,$u);}
 public function update(int $t,int $id,array $i,int $u):void{if(!$this->find($t,$id))throw new RuntimeException('Fresh Food business not found.');$d=$this->validate($i);if($this->m->nameExists($t,$d['business_name'],$id))throw new RuntimeException('A Fresh Food business with this name already exists.');$d['business_slug']=$this->slug($t,$this->slugify($d['business_name']),$id);$this->m->update($t,$id,$d,$u);}
 public function delete(int $t,int $id,int $u):void{if(!$this->find($t,$id))throw new RuntimeException('Fresh Food business not found.');$this->m->softDelete($t,$id,$u);} public function restore(int $t,int $id,int $u):void{if(!$this->findDeleted($t,$id))throw new RuntimeException('Deleted Fresh Food business not found.');$this->m->restore($t,$id,$u);}
 public function saveHours(int $t,int $id,array $i,int $u):void{if(!$this->find($t,$id))throw new RuntimeException('Fresh Food business not found.');$days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];$h=[];for($d=0;$d<=6;$d++){ $closed=!empty($i['is_closed'][$d]);$open=$closed?null:$this->time($i['opens_at'][$d]??null);$close=$closed?null:$this->time($i['closes_at'][$d]??null);if(!$closed&&($open===null||$close===null))throw new RuntimeException($days[$d].' must have both opening and closing times, or be marked closed.');$h[$d]=['opens_at'=>$open,'closes_at'=>$close,'is_closed'=>$closed?1:0,'created_by'=>$u,'updated_by'=>$u];}$this->m->replaceHours($t,$id,$h);}
 public function locations():array{return ['state'=>['Manipur'],'districts'=>['Bishnupur','Chandel','Churachandpur','Imphal East','Imphal West','Jiribam','Kakching','Kamjong','Kangpokpi','Noney','Pherzawl','Senapati','Tamenglong','Tengnoupal','Thoubal','Ukhrul'],'cities'=>['Imphal','Bishnupur','Chandel','Churachandpur','Jiribam','Kakching','Kamjong','Kangpokpi','Noney','Pherzawl','Senapati','Tamenglong','Moreh','Thoubal','Ukhrul']];}
 private function validate(array $i):array{$l=$this->locations();$d=['business_name'=>$this->str($i['business_name']??''),'phone'=>$this->str($i['phone']??''),'email'=>$this->str($i['email']??''),'address'=>$this->str($i['address']??''),'city'=>$this->str($i['city']??''),'district'=>$this->str($i['district']??''),'state'=>$this->str($i['state']??'')?:'Manipur','postal_code'=>$this->str($i['postal_code']??''),'description'=>$this->str($i['description']??''),'latitude'=>$this->coord($i['latitude']??null,-90,90),'longitude'=>$this->coord($i['longitude']??null,-180,180),'delivery_available'=>!empty($i['delivery_available'])?1:0,'pickup_available'=>!empty($i['pickup_available'])?1:0,'max_delivery_distance_km'=>$this->decimal($i['max_delivery_distance_km']??null),'minimum_delivery_fee'=>$this->money($i['minimum_delivery_fee']??20),'included_delivery_distance_km'=>$this->decimal($i['included_delivery_distance_km']??3),'additional_delivery_fee_per_km'=>$this->money($i['additional_delivery_fee_per_km']??10),'preorder_enabled'=>!empty($i['preorder_enabled'])?1:0,'preorder_min_advance_hours'=>max(1,(int)($i['preorder_min_advance_hours']??24)),'preorder_delivery_fee'=>$this->money($i['preorder_delivery_fee']??20),'estimated_packing_minutes_min'=>max(1,(int)($i['estimated_packing_minutes_min']??10)),'estimated_packing_minutes_max'=>max(1,(int)($i['estimated_packing_minutes_max']??20)),'accepting_orders'=>!empty($i['accepting_orders'])?1:0,'status'=>$this->str($i['status']??'Active')?:'Active'];if(!$d['business_name'])throw new RuntimeException('Fresh Food business name is required.');if(!in_array($d['state'],$l['state'],true)||!in_array($d['district'],$l['districts'],true)||!in_array($d['city'],$l['cities'],true))throw new RuntimeException('Please select a valid Manipur location.');if(($d['latitude']===null)!==($d['longitude']===null))throw new RuntimeException('Latitude and longitude must be provided together.');if($d['included_delivery_distance_km']===null||$d['included_delivery_distance_km']<=0)throw new RuntimeException('Included delivery distance must be greater than zero.');if($d['estimated_packing_minutes_max']<$d['estimated_packing_minutes_min'])throw new RuntimeException('Maximum packing time cannot be less than minimum packing time.');if($d['status']&&!in_array($d['status'],['Active','Inactive','Suspended'],true))throw new RuntimeException('Invalid Fresh Food status.');return $d;}
 private function slug(int $t,string $base,?int $ignore=null):string{$base=$base?:'fresh-food';$c=$base;$n=2;while($this->m->slugExists($t,$c,$ignore))$c=$base.'-'.$n++;return $c;}private function slugify(string $v):string{$v=strtolower(trim($v));$v=preg_replace('/[^a-z0-9]+/','-',$v)??'';return trim($v,'-');}private function str(mixed $v):?string{$v=trim((string)$v);return $v===''?null:$v;}private function money(mixed $v):string{$n=(float)$v;if($n<0)throw new RuntimeException('Amounts cannot be negative.');return number_format($n,2,'.','');}private function decimal(mixed $v):?string{if($v===null||trim((string)$v)==='')return null;$n=(float)$v;if($n<0)throw new RuntimeException('Distance cannot be negative.');return number_format($n,2,'.','');}private function coord(mixed $v,float $min,float $max):?string{if($v===null||trim((string)$v)==='')return null;if(!is_numeric($v)||(float)$v<$min||(float)$v>$max)throw new RuntimeException('Invalid location coordinates.');return number_format((float)$v,7,'.','');}private function time(mixed $v):?string{$v=trim((string)$v);if($v==='')return null;if(!preg_match('/^([01]\d|2[0-3]):[0-5]\d(:[0-5]\d)?$/',$v))throw new RuntimeException('Invalid opening/closing time.');return strlen($v)===5?$v.':00':$v;}
}
